// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: nilchain/nilchain/v1/params.proto

package types

import (
	cosmossdk_io_math "cosmossdk.io/math"
	fmt "fmt"
	types "github.com/cosmos/cosmos-sdk/types"
	_ "github.com/cosmos/cosmos-sdk/types/tx/amino"
	_ "github.com/cosmos/gogoproto/gogoproto"
	proto "github.com/cosmos/gogoproto/proto"
	io "io"
	math "math"
	math_bits "math/bits"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

// Params defines the parameters for the module.
type Params struct {
	BaseStripeCost        uint64                      `protobuf:"varint,1,opt,name=base_stripe_cost,json=baseStripeCost,proto3" json:"base_stripe_cost,omitempty"`
	HalvingInterval       uint64                      `protobuf:"varint,2,opt,name=halving_interval,json=halvingInterval,proto3" json:"halving_interval,omitempty"`
	Eip712ChainId         uint64                      `protobuf:"varint,3,opt,name=eip712_chain_id,json=eip712ChainId,proto3" json:"eip712_chain_id,omitempty"`
	StoragePrice          cosmossdk_io_math.LegacyDec `protobuf:"bytes,4,opt,name=storage_price,json=storagePrice,proto3,customtype=cosmossdk.io/math.LegacyDec" json:"storage_price"`
	DealCreationFee       types.Coin                  `protobuf:"bytes,5,opt,name=deal_creation_fee,json=dealCreationFee,proto3" json:"deal_creation_fee"`
	MinDurationBlocks     uint64                      `protobuf:"varint,6,opt,name=min_duration_blocks,json=minDurationBlocks,proto3" json:"min_duration_blocks,omitempty"`
	BaseRetrievalFee      types.Coin                  `protobuf:"bytes,7,opt,name=base_retrieval_fee,json=baseRetrievalFee,proto3" json:"base_retrieval_fee"`
	RetrievalPricePerBlob types.Coin                  `protobuf:"bytes,8,opt,name=retrieval_price_per_blob,json=retrievalPricePerBlob,proto3" json:"retrieval_price_per_blob"`
	RetrievalBurnBps      uint64                      `protobuf:"varint,9,opt,name=retrieval_burn_bps,json=retrievalBurnBps,proto3" json:"retrieval_burn_bps,omitempty"`
	// Length of the elasticity spend window ("month") in blocks.
	// When the chain height exceeds spend_window_start_height + month_len_blocks,
	// the window resets and spend_window_spent returns to 0.
	MonthLenBlocks uint64 `protobuf:"varint,10,opt,name=month_len_blocks,json=monthLenBlocks,proto3" json:"month_len_blocks,omitempty"`
	// --- Unified Liveness / Quotas (Mode 1 + Mode 2) ---
	// Length of a liveness epoch in blocks. Used for deterministic challenge derivation.
	EpochLenBlocks uint64 `protobuf:"varint,11,opt,name=epoch_len_blocks,json=epochLenBlocks,proto3" json:"epoch_len_blocks,omitempty"`
	// Proof quota per epoch, in basis points of slot-responsible bytes.
	// See `rfcs/rfc-challenge-derivation-and-quotas.md`.
	QuotaBpsPerEpochHot  uint64 `protobuf:"varint,12,opt,name=quota_bps_per_epoch_hot,json=quotaBpsPerEpochHot,proto3" json:"quota_bps_per_epoch_hot,omitempty"`
	QuotaBpsPerEpochCold uint64 `protobuf:"varint,13,opt,name=quota_bps_per_epoch_cold,json=quotaBpsPerEpochCold,proto3" json:"quota_bps_per_epoch_cold,omitempty"`
	// Minimum/maximum number of blobs required per epoch per assignment.
	QuotaMinBlobs uint64 `protobuf:"varint,14,opt,name=quota_min_blobs,json=quotaMinBlobs,proto3" json:"quota_min_blobs,omitempty"`
	QuotaMaxBlobs uint64 `protobuf:"varint,15,opt,name=quota_max_blobs,json=quotaMaxBlobs,proto3" json:"quota_max_blobs,omitempty"`
	// Cap on how much of the quota can be satisfied via organic retrieval credits.
	CreditCapBps uint64 `protobuf:"varint,16,opt,name=credit_cap_bps,json=creditCapBps,proto3" json:"credit_cap_bps,omitempty"`
	// Evict (trigger repair) after this many consecutive missed epochs.
	EvictAfterMissedEpochs uint64 `protobuf:"varint,17,opt,name=evict_after_missed_epochs,json=evictAfterMissedEpochs,proto3" json:"evict_after_missed_epochs,omitempty"`
	// Renewal grace window: allow extending an expired deal until
	// `current_height <= end_block + deal_extension_grace_blocks`.
	//
	// See `rfcs/rfc-deal-expiry-and-extension.md`.
	DealExtensionGraceBlocks uint64 `protobuf:"varint,18,opt,name=deal_extension_grace_blocks,json=dealExtensionGraceBlocks,proto3" json:"deal_extension_grace_blocks,omitempty"`
	// Maximum TTL for sponsored retrieval vouchers, in blocks.
	// 0 disables the TTL bound (not recommended).
	//
	// See `rfcs/rfc-retrieval-access-control-public-deals-and-vouchers.md`.
	VoucherMaxTtlBlocks uint64 `protobuf:"varint,19,opt,name=voucher_max_ttl_blocks,json=voucherMaxTtlBlocks,proto3" json:"voucher_max_ttl_blocks,omitempty"`
	// --- Protocol audit budget (minted, deterministic; see RFCs) ---
	// audit_budget_mint = min(
	//   ceil(audit_budget_bps / 10_000 * epoch_slot_rent),
	//   ceil(audit_budget_cap_bps / 10_000 * epoch_slot_rent),
	// )
	AuditBudgetBps    uint64 `protobuf:"varint,20,opt,name=audit_budget_bps,json=auditBudgetBps,proto3" json:"audit_budget_bps,omitempty"`
	AuditBudgetCapBps uint64 `protobuf:"varint,21,opt,name=audit_budget_cap_bps,json=auditBudgetCapBps,proto3" json:"audit_budget_cap_bps,omitempty"`
	// Maximum number of epochs worth of unused budget that may carry forward.
	// 0 means "no carryover" (cap to 1 epoch).
	AuditBudgetCarryoverEpochs uint64 `protobuf:"varint,22,opt,name=audit_budget_carryover_epochs,json=auditBudgetCarryoverEpochs,proto3" json:"audit_budget_carryover_epochs,omitempty"`
	// --- Base reward pool emission schedule (see `rfcs/rfc-base-reward-pool-and-emissions.md`) ---
	EmissionStartHeight             uint64 `protobuf:"varint,23,opt,name=emission_start_height,json=emissionStartHeight,proto3" json:"emission_start_height,omitempty"`
	BaseRewardHalvingIntervalBlocks uint64 `protobuf:"varint,24,opt,name=base_reward_halving_interval_blocks,json=baseRewardHalvingIntervalBlocks,proto3" json:"base_reward_halving_interval_blocks,omitempty"`
	BaseRewardBpsStart              uint64 `protobuf:"varint,25,opt,name=base_reward_bps_start,json=baseRewardBpsStart,proto3" json:"base_reward_bps_start,omitempty"`
	BaseRewardBpsTail               uint64 `protobuf:"varint,26,opt,name=base_reward_bps_tail,json=baseRewardBpsTail,proto3" json:"base_reward_bps_tail,omitempty"`
}

func (m *Params) Reset()         { *m = Params{} }
func (m *Params) String() string { return proto.CompactTextString(m) }
func (*Params) ProtoMessage()    {}
func (*Params) Descriptor() ([]byte, []int) {
	return fileDescriptor_8ae414f9073848ab, []int{0}
}
func (m *Params) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *Params) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_Params.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *Params) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Params.Merge(m, src)
}
func (m *Params) XXX_Size() int {
	return m.Size()
}
func (m *Params) XXX_DiscardUnknown() {
	xxx_messageInfo_Params.DiscardUnknown(m)
}

var xxx_messageInfo_Params proto.InternalMessageInfo

func (m *Params) GetBaseStripeCost() uint64 {
	if m != nil {
		return m.BaseStripeCost
	}
	return 0
}

func (m *Params) GetHalvingInterval() uint64 {
	if m != nil {
		return m.HalvingInterval
	}
	return 0
}

func (m *Params) GetEip712ChainId() uint64 {
	if m != nil {
		return m.Eip712ChainId
	}
	return 0
}

func (m *Params) GetDealCreationFee() types.Coin {
	if m != nil {
		return m.DealCreationFee
	}
	return types.Coin{}
}

func (m *Params) GetMinDurationBlocks() uint64 {
	if m != nil {
		return m.MinDurationBlocks
	}
	return 0
}

func (m *Params) GetBaseRetrievalFee() types.Coin {
	if m != nil {
		return m.BaseRetrievalFee
	}
	return types.Coin{}
}

func (m *Params) GetRetrievalPricePerBlob() types.Coin {
	if m != nil {
		return m.RetrievalPricePerBlob
	}
	return types.Coin{}
}

func (m *Params) GetRetrievalBurnBps() uint64 {
	if m != nil {
		return m.RetrievalBurnBps
	}
	return 0
}

func (m *Params) GetMonthLenBlocks() uint64 {
	if m != nil {
		return m.MonthLenBlocks
	}
	return 0
}

func (m *Params) GetEpochLenBlocks() uint64 {
	if m != nil {
		return m.EpochLenBlocks
	}
	return 0
}

func (m *Params) GetQuotaBpsPerEpochHot() uint64 {
	if m != nil {
		return m.QuotaBpsPerEpochHot
	}
	return 0
}

func (m *Params) GetQuotaBpsPerEpochCold() uint64 {
	if m != nil {
		return m.QuotaBpsPerEpochCold
	}
	return 0
}

func (m *Params) GetQuotaMinBlobs() uint64 {
	if m != nil {
		return m.QuotaMinBlobs
	}
	return 0
}

func (m *Params) GetQuotaMaxBlobs() uint64 {
	if m != nil {
		return m.QuotaMaxBlobs
	}
	return 0
}

func (m *Params) GetCreditCapBps() uint64 {
	if m != nil {
		return m.CreditCapBps
	}
	return 0
}

func (m *Params) GetEvictAfterMissedEpochs() uint64 {
	if m != nil {
		return m.EvictAfterMissedEpochs
	}
	return 0
}

func (m *Params) GetDealExtensionGraceBlocks() uint64 {
	if m != nil {
		return m.DealExtensionGraceBlocks
	}
	return 0
}

func (m *Params) GetVoucherMaxTtlBlocks() uint64 {
	if m != nil {
		return m.VoucherMaxTtlBlocks
	}
	return 0
}

func (m *Params) GetAuditBudgetBps() uint64 {
	if m != nil {
		return m.AuditBudgetBps
	}
	return 0
}

func (m *Params) GetAuditBudgetCapBps() uint64 {
	if m != nil {
		return m.AuditBudgetCapBps
	}
	return 0
}

func (m *Params) GetAuditBudgetCarryoverEpochs() uint64 {
	if m != nil {
		return m.AuditBudgetCarryoverEpochs
	}
	return 0
}

func (m *Params) GetEmissionStartHeight() uint64 {
	if m != nil {
		return m.EmissionStartHeight
	}
	return 0
}

func (m *Params) GetBaseRewardHalvingIntervalBlocks() uint64 {
	if m != nil {
		return m.BaseRewardHalvingIntervalBlocks
	}
	return 0
}

func (m *Params) GetBaseRewardBpsStart() uint64 {
	if m != nil {
		return m.BaseRewardBpsStart
	}
	return 0
}

func (m *Params) GetBaseRewardBpsTail() uint64 {
	if m != nil {
		return m.BaseRewardBpsTail
	}
	return 0
}

func init() {
	proto.RegisterType((*Params)(nil), "nilchain.nilchain.v1.Params")
}

func init() { proto.RegisterFile("nilchain/nilchain/v1/params.proto", fileDescriptor_8ae414f9073848ab) }

var fileDescriptor_8ae414f9073848ab = []byte{
	// 855 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x8c, 0x55, 0x4d, 0x6f, 0x1b, 0x45,
	0x18, 0x8e, 0x21, 0x04, 0x3a, 0xf9, 0x72, 0x36, 0x4e, 0x3a, 0x71, 0x85, 0x13, 0x08, 0x42, 0x06,
	0xa1, 0x5d, 0x39, 0x41, 0x20, 0x90, 0x38, 0x74, 0xdd, 0x42, 0x2a, 0x12, 0x29, 0x4a, 0x7b, 0x40,
	0x5c, 0x46, 0xb3, 0xb3, 0x6f, 0xed, 0x51, 0x77, 0x77, 0x96, 0x99, 0xf1, 0xe2, 0xfc, 0x05, 0x4e,
	0xfc, 0x04, 0x7e, 0x02, 0x12, 0x7f, 0xa2, 0xc7, 0x1e, 0x11, 0x87, 0x0a, 0x25, 0x07, 0xf8, 0x19,
	0xd5, 0xbc, 0xb3, 0x6b, 0xc7, 0x51, 0x0f, 0xb9, 0x58, 0xa3, 0xf7, 0x79, 0x9e, 0xf7, 0xe3, 0x99,
	0x77, 0xc7, 0xe4, 0xa3, 0x42, 0x66, 0x62, 0xcc, 0x65, 0x11, 0xcd, 0x0e, 0xd5, 0x20, 0x2a, 0xb9,
	0xe6, 0xb9, 0x09, 0x4b, 0xad, 0xac, 0x0a, 0x3a, 0x0d, 0x12, 0xce, 0x0e, 0xd5, 0xa0, 0xbb, 0xc5,
	0x73, 0x59, 0xa8, 0x08, 0x7f, 0x3d, 0xb1, 0xdb, 0x19, 0xa9, 0x91, 0xc2, 0x63, 0xe4, 0x4e, 0x75,
	0xb4, 0x27, 0x94, 0xc9, 0x95, 0x89, 0x12, 0x6e, 0x20, 0xaa, 0x06, 0x09, 0x58, 0x3e, 0x88, 0x84,
	0x92, 0x85, 0xc7, 0x3f, 0xfe, 0x6b, 0x95, 0xac, 0x9c, 0x63, 0xbd, 0xa0, 0x4f, 0xda, 0x8e, 0xc5,
	0x8c, 0xd5, 0xb2, 0x04, 0x26, 0x94, 0xb1, 0xb4, 0x75, 0xd0, 0xea, 0x2f, 0x5f, 0x6c, 0xb8, 0xf8,
	0x53, 0x0c, 0x0f, 0x95, 0xb1, 0xc1, 0x67, 0xa4, 0x3d, 0xe6, 0x59, 0x25, 0x8b, 0x11, 0x93, 0x85,
	0x05, 0x5d, 0xf1, 0x8c, 0xbe, 0x83, 0xcc, 0xcd, 0x3a, 0xfe, 0xa4, 0x0e, 0x07, 0x9f, 0x92, 0x4d,
	0x90, 0xe5, 0xd7, 0x83, 0x23, 0x86, 0xbd, 0x33, 0x99, 0xd2, 0x77, 0x91, 0xb9, 0xee, 0xc3, 0x43,
	0x17, 0x7d, 0x92, 0x06, 0x27, 0x64, 0xdd, 0x58, 0xa5, 0xf9, 0x08, 0x58, 0xa9, 0xa5, 0x00, 0xba,
	0x7c, 0xd0, 0xea, 0xdf, 0x8b, 0x0f, 0x5f, 0xbe, 0xde, 0x5f, 0xfa, 0xe7, 0xf5, 0xfe, 0x03, 0x3f,
	0x86, 0x49, 0x5f, 0x84, 0x52, 0x45, 0x39, 0xb7, 0xe3, 0xf0, 0x14, 0x46, 0x5c, 0x5c, 0x3e, 0x02,
	0x71, 0xb1, 0x56, 0x2b, 0xcf, 0x9d, 0x30, 0xf8, 0x91, 0x6c, 0xa5, 0xc0, 0x33, 0x26, 0x34, 0x70,
	0x2b, 0x55, 0xc1, 0x9e, 0x03, 0xd0, 0xf7, 0x0e, 0x5a, 0xfd, 0xd5, 0xa3, 0xbd, 0xd0, 0xa7, 0x09,
	0xdd, 0x3c, 0x61, 0xed, 0x46, 0x38, 0x54, 0xb2, 0x88, 0x97, 0x5d, 0xa1, 0x8b, 0x4d, 0xa7, 0x1c,
	0xd6, 0xc2, 0xef, 0x01, 0x82, 0x90, 0x6c, 0xe7, 0xb2, 0x60, 0xe9, 0x44, 0xfb, 0x5c, 0x49, 0xa6,
	0xc4, 0x0b, 0x43, 0x57, 0x70, 0x84, 0xad, 0x5c, 0x16, 0x8f, 0x6a, 0x24, 0x46, 0x20, 0x38, 0x23,
	0x01, 0x7a, 0xa8, 0xc1, 0x6a, 0x09, 0x15, 0xcf, 0xb0, 0xfa, 0xfb, 0x77, 0xab, 0x8e, 0xf6, 0x5f,
	0x34, 0x4a, 0x57, 0xfe, 0x27, 0x42, 0xe7, 0x99, 0xd0, 0x17, 0x56, 0x82, 0x76, 0x5d, 0x24, 0xf4,
	0x83, 0xbb, 0x25, 0xdd, 0x99, 0x25, 0x40, 0x7b, 0xce, 0x41, 0xc7, 0x99, 0x4a, 0x82, 0x2f, 0x48,
	0x30, 0xcf, 0x9c, 0x4c, 0x74, 0xc1, 0x92, 0xd2, 0xd0, 0x7b, 0x38, 0x57, 0x7b, 0x86, 0xc4, 0x13,
	0x5d, 0xc4, 0x25, 0xae, 0x46, 0xae, 0x0a, 0x3b, 0x66, 0x19, 0xcc, 0x3c, 0x20, 0x7e, 0x35, 0x30,
	0x7e, 0x0a, 0x8d, 0x01, 0x7d, 0xd2, 0x86, 0x52, 0x89, 0x05, 0xe6, 0xaa, 0x67, 0x62, 0x7c, 0xce,
	0xfc, 0x92, 0xdc, 0xff, 0x65, 0xa2, 0x2c, 0x77, 0x85, 0x71, 0x2a, 0xaf, 0x1b, 0x2b, 0x4b, 0xd7,
	0x50, 0xb0, 0x8d, 0x70, 0x5c, 0x9a, 0x73, 0xd0, 0x8f, 0x1d, 0x76, 0xa2, 0x6c, 0xf0, 0x15, 0xa1,
	0x6f, 0x53, 0x09, 0x95, 0xa5, 0x74, 0x1d, 0x65, 0x9d, 0xdb, 0xb2, 0xa1, 0xca, 0x52, 0xb7, 0x87,
	0x5e, 0xe7, 0xae, 0xd3, 0xf9, 0x67, 0xe8, 0x86, 0xdf, 0x43, 0x0c, 0x9f, 0x49, 0xd7, 0x56, 0x62,
	0x6e, 0xf0, 0xf8, 0xb4, 0xe6, 0x6d, 0xde, 0xe4, 0xf1, 0xa9, 0xe7, 0x7d, 0x42, 0x36, 0x84, 0x86,
	0x54, 0x5a, 0x26, 0x78, 0x89, 0xde, 0xb5, 0x91, 0xb6, 0xe6, 0xa3, 0x43, 0x5e, 0x3a, 0xdf, 0xbe,
	0x21, 0x7b, 0x50, 0x49, 0x61, 0x19, 0x7f, 0x6e, 0x41, 0xb3, 0x5c, 0x1a, 0x03, 0xa9, 0x6f, 0xd9,
	0xd0, 0x2d, 0x14, 0xec, 0x22, 0xe1, 0xa1, 0xc3, 0xcf, 0x10, 0xc6, 0x9e, 0x4d, 0xf0, 0x1d, 0x79,
	0x80, 0x6b, 0x0c, 0x53, 0x0b, 0x85, 0x71, 0xbb, 0x37, 0xd2, 0x5c, 0x40, 0xe3, 0x69, 0x80, 0x62,
	0xea, 0x28, 0x8f, 0x1b, 0xc6, 0x0f, 0x8e, 0x50, 0xbb, 0x7b, 0x4c, 0x76, 0x2b, 0x35, 0x11, 0x63,
	0x57, 0x95, 0x4f, 0x99, 0xb5, 0x59, 0xa3, 0xdc, 0xf6, 0xe6, 0xd6, 0xe8, 0x19, 0x9f, 0x3e, 0xb3,
	0xd9, 0xfc, 0xf2, 0xf8, 0xc4, 0xcd, 0x94, 0x4c, 0xd2, 0x11, 0x58, 0x1c, 0xab, 0xe3, 0x2f, 0x0f,
	0xe3, 0x31, 0x86, 0xdd, 0x60, 0x11, 0xe9, 0x2c, 0x30, 0x1b, 0x13, 0x76, 0xfc, 0x87, 0x71, 0x83,
	0x5d, 0x3b, 0xf1, 0x90, 0x7c, 0x78, 0x4b, 0xa0, 0xf5, 0xa5, 0xaa, 0x9a, 0x0b, 0x34, 0x74, 0x17,
	0x95, 0xdd, 0x05, 0x65, 0x4d, 0xa9, 0x1d, 0x39, 0x22, 0x3b, 0xe0, 0x1c, 0x74, 0x5e, 0x18, 0xcb,
	0xb5, 0x65, 0x63, 0x90, 0xa3, 0xb1, 0xa5, 0xf7, 0xfd, 0x44, 0x0d, 0xf8, 0xd4, 0x61, 0x27, 0x08,
	0x05, 0xa7, 0xe4, 0xb0, 0xfe, 0x1e, 0x7f, 0xe5, 0x3a, 0x65, 0xb7, 0x5f, 0xad, 0xc6, 0x13, 0x8a,
	0x19, 0xf6, 0xfd, 0xf7, 0xe7, 0x98, 0x27, 0x8b, 0xcf, 0x58, 0xed, 0xcf, 0x80, 0xec, 0xdc, 0xcc,
	0xe6, 0x56, 0x10, 0x1b, 0xa1, 0x7b, 0xa8, 0x0f, 0xe6, 0xfa, 0xb8, 0x34, 0xd8, 0x86, 0x33, 0xea,
	0xb6, 0xc4, 0x72, 0x99, 0xd1, 0xae, 0x37, 0x6a, 0x41, 0xf1, 0x8c, 0xcb, 0xec, 0xdb, 0xc3, 0xff,
	0xff, 0xd8, 0x6f, 0xfd, 0xf6, 0xdf, 0x9f, 0x9f, 0x77, 0x67, 0x7f, 0x09, 0xd3, 0xf9, 0xbf, 0x83,
	0x7f, 0xaa, 0xe3, 0xe3, 0x97, 0x57, 0xbd, 0xd6, 0xab, 0xab, 0x5e, 0xeb, 0xdf, 0xab, 0x5e, 0xeb,
	0xf7, 0xeb, 0xde, 0xd2, 0xab, 0xeb, 0xde, 0xd2, 0xdf, 0xd7, 0xbd, 0xa5, 0x9f, 0xf7, 0xde, 0xa6,
	0xb2, 0x97, 0x25, 0x98, 0x64, 0x05, 0x5f, 0xfc, 0xe3, 0x37, 0x01, 0x00, 0x00, 0xff, 0xff, 0x78,
	0xb6, 0xce, 0x19, 0x75, 0x06, 0x00, 0x00,
}

func (this *Params) Equal(that interface{}) bool {
	if that == nil {
		return this == nil
	}

	that1, ok := that.(*Params)
	if !ok {
		that2, ok := that.(Params)
		if ok {
			that1 = &that2
		} else {
			return false
		}
	}
	if that1 == nil {
		return this == nil
	} else if this == nil {
		return false
	}
	if this.BaseStripeCost != that1.BaseStripeCost {
		return false
	}
	if this.HalvingInterval != that1.HalvingInterval {
		return false
	}
	if this.Eip712ChainId != that1.Eip712ChainId {
		return false
	}
	if !this.StoragePrice.Equal(that1.StoragePrice) {
		return false
	}
	if !this.DealCreationFee.Equal(&that1.DealCreationFee) {
		return false
	}
	if this.MinDurationBlocks != that1.MinDurationBlocks {
		return false
	}
	if !this.BaseRetrievalFee.Equal(&that1.BaseRetrievalFee) {
		return false
	}
	if !this.RetrievalPricePerBlob.Equal(&that1.RetrievalPricePerBlob) {
		return false
	}
	if this.RetrievalBurnBps != that1.RetrievalBurnBps {
		return false
	}
	if this.MonthLenBlocks != that1.MonthLenBlocks {
		return false
	}
	if this.EpochLenBlocks != that1.EpochLenBlocks {
		return false
	}
	if this.QuotaBpsPerEpochHot != that1.QuotaBpsPerEpochHot {
		return false
	}
	if this.QuotaBpsPerEpochCold != that1.QuotaBpsPerEpochCold {
		return false
	}
	if this.QuotaMinBlobs != that1.QuotaMinBlobs {
		return false
	}
	if this.QuotaMaxBlobs != that1.QuotaMaxBlobs {
		return false
	}
	if this.CreditCapBps != that1.CreditCapBps {
		return false
	}
	if this.EvictAfterMissedEpochs != that1.EvictAfterMissedEpochs {
		return false
	}
	if this.DealExtensionGraceBlocks != that1.DealExtensionGraceBlocks {
		return false
	}
	if this.VoucherMaxTtlBlocks != that1.VoucherMaxTtlBlocks {
		return false
	}
	if this.AuditBudgetBps != that1.AuditBudgetBps {
		return false
	}
	if this.AuditBudgetCapBps != that1.AuditBudgetCapBps {
		return false
	}
	if this.AuditBudgetCarryoverEpochs != that1.AuditBudgetCarryoverEpochs {
		return false
	}
	if this.EmissionStartHeight != that1.EmissionStartHeight {
		return false
	}
	if this.BaseRewardHalvingIntervalBlocks != that1.BaseRewardHalvingIntervalBlocks {
		return false
	}
	if this.BaseRewardBpsStart != that1.BaseRewardBpsStart {
		return false
	}
	if this.BaseRewardBpsTail != that1.BaseRewardBpsTail {
		return false
	}
	return true
}
func (m *Params) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *Params) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *Params) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.BaseRewardBpsTail != 0 {
		i = encodeVarintParams(dAtA, i, uint64(m.BaseRewardBpsTail))
		i--
		dAtA[i] = 0x1
		i--
		dAtA[i] = 0xd0
	}
	if m.BaseRewardBpsStart != 0 {
		i = encodeVarintParams(dAtA, i, uint64(m.BaseRewardBpsStart))
		i--
		dAtA[i] = 0x1
		i--
		dAtA[i] = 0xc8
	}
	if m.BaseRewardHalvingIntervalBlocks != 0 {
		i = encodeVarintParams(dAtA, i, uint64(m.BaseRewardHalvingIntervalBlocks))
		i--
		dAtA[i] = 0x1
		i--
		dAtA[i] = 0xc0
	}
	if m.EmissionStartHeight != 0 {
		i = encodeVarintParams(dAtA, i, uint64(m.EmissionStartHeight))
		i--
		dAtA[i] = 0x1
		i--
		dAtA[i] = 0xb8
	}
	if m.AuditBudgetCarryoverEpochs != 0 {
		i = encodeVarintParams(dAtA, i, uint64(m.AuditBudgetCarryoverEpochs))
		i--
		dAtA[i] = 0x1
		i--
		dAtA[i] = 0xb0
	}
	if m.AuditBudgetCapBps != 0 {
		i = encodeVarintParams(dAtA, i, uint64(m.AuditBudgetCapBps))
		i--
		dAtA[i] = 0x1
		i--
		dAtA[i] = 0xa8
	}
	if m.AuditBudgetBps != 0 {
		i = encodeVarintParams(dAtA, i, uint64(m.AuditBudgetBps))
		i--
		dAtA[i] = 0x1
		i--
		dAtA[i] = 0xa0
	}
	if m.VoucherMaxTtlBlocks != 0 {
		i = encodeVarintParams(dAtA, i, uint64(m.VoucherMaxTtlBlocks))
		i--
		dAtA[i] = 0x1
		i--
		dAtA[i] = 0x98
	}
	if m.DealExtensionGraceBlocks != 0 {
		i = encodeVarintParams(dAtA, i, uint64(m.DealExtensionGraceBlocks))
		i--
		dAtA[i] = 0x1
		i--
		dAtA[i] = 0x90
	}
	if m.EvictAfterMissedEpochs != 0 {
		i = encodeVarintParams(dAtA, i, uint64(m.EvictAfterMissedEpochs))
		i--
		dAtA[i] = 0x1
		i--
		dAtA[i] = 0x88
	}
	if m.CreditCapBps != 0 {
		i = encodeVarintParams(dAtA, i, uint64(m.CreditCapBps))
		i--
		dAtA[i] = 0x1
		i--
		dAtA[i] = 0x80
	}
	if m.QuotaMaxBlobs != 0 {
		i = encodeVarintParams(dAtA, i, uint64(m.QuotaMaxBlobs))
		i--
		dAtA[i] = 0x78
	}
	if m.QuotaMinBlobs != 0 {
		i = encodeVarintParams(dAtA, i, uint64(m.QuotaMinBlobs))
		i--
		dAtA[i] = 0x70
	}
	if m.QuotaBpsPerEpochCold != 0 {
		i = encodeVarintParams(dAtA, i, uint64(m.QuotaBpsPerEpochCold))
		i--
		dAtA[i] = 0x68
	}
	if m.QuotaBpsPerEpochHot != 0 {
		i = encodeVarintParams(dAtA, i, uint64(m.QuotaBpsPerEpochHot))
		i--
		dAtA[i] = 0x60
	}
	if m.EpochLenBlocks != 0 {
		i = encodeVarintParams(dAtA, i, uint64(m.EpochLenBlocks))
		i--
		dAtA[i] = 0x58
	}
	if m.MonthLenBlocks != 0 {
		i = encodeVarintParams(dAtA, i, uint64(m.MonthLenBlocks))
		i--
		dAtA[i] = 0x50
	}
	if m.RetrievalBurnBps != 0 {
		i = encodeVarintParams(dAtA, i, uint64(m.RetrievalBurnBps))
		i--
		dAtA[i] = 0x48
	}
	{
		size, err := m.RetrievalPricePerBlob.MarshalToSizedBuffer(dAtA[:i])
		if err != nil {
			return 0, err
		}
		i -= size
		i = encodeVarintParams(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0x42
	{
		size, err := m.BaseRetrievalFee.MarshalToSizedBuffer(dAtA[:i])
		if err != nil {
			return 0, err
		}
		i -= size
		i = encodeVarintParams(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0x3a
	if m.MinDurationBlocks != 0 {
		i = encodeVarintParams(dAtA, i, uint64(m.MinDurationBlocks))
		i--
		dAtA[i] = 0x30
	}
	{
		size, err := m.DealCreationFee.MarshalToSizedBuffer(dAtA[:i])
		if err != nil {
			return 0, err
		}
		i -= size
		i = encodeVarintParams(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0x2a
	{
		size := m.StoragePrice.Size()
		i -= size
		if _, err := m.StoragePrice.MarshalTo(dAtA[i:]); err != nil {
			return 0, err
		}
		i = encodeVarintParams(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0x22
	if m.Eip712ChainId != 0 {
		i = encodeVarintParams(dAtA, i, uint64(m.Eip712ChainId))
		i--
		dAtA[i] = 0x18
	}
	if m.HalvingInterval != 0 {
		i = encodeVarintParams(dAtA, i, uint64(m.HalvingInterval))
		i--
		dAtA[i] = 0x10
	}
	if m.BaseStripeCost != 0 {
		i = encodeVarintParams(dAtA, i, uint64(m.BaseStripeCost))
		i--
		dAtA[i] = 0x8
	}
	return len(dAtA) - i, nil
}

func encodeVarintParams(dAtA []byte, offset int, v uint64) int {
	offset -= sovParams(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *Params) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.BaseStripeCost != 0 {
		n += 1 + sovParams(uint64(m.BaseStripeCost))
	}
	if m.HalvingInterval != 0 {
		n += 1 + sovParams(uint64(m.HalvingInterval))
	}
	if m.Eip712ChainId != 0 {
		n += 1 + sovParams(uint64(m.Eip712ChainId))
	}
	l = m.StoragePrice.Size()
	n += 1 + l + sovParams(uint64(l))
	l = m.DealCreationFee.Size()
	n += 1 + l + sovParams(uint64(l))
	if m.MinDurationBlocks != 0 {
		n += 1 + sovParams(uint64(m.MinDurationBlocks))
	}
	l = m.BaseRetrievalFee.Size()
	n += 1 + l + sovParams(uint64(l))
	l = m.RetrievalPricePerBlob.Size()
	n += 1 + l + sovParams(uint64(l))
	if m.RetrievalBurnBps != 0 {
		n += 1 + sovParams(uint64(m.RetrievalBurnBps))
	}
	if m.MonthLenBlocks != 0 {
		n += 1 + sovParams(uint64(m.MonthLenBlocks))
	}
	if m.EpochLenBlocks != 0 {
		n += 1 + sovParams(uint64(m.EpochLenBlocks))
	}
	if m.QuotaBpsPerEpochHot != 0 {
		n += 1 + sovParams(uint64(m.QuotaBpsPerEpochHot))
	}
	if m.QuotaBpsPerEpochCold != 0 {
		n += 1 + sovParams(uint64(m.QuotaBpsPerEpochCold))
	}
	if m.QuotaMinBlobs != 0 {
		n += 1 + sovParams(uint64(m.QuotaMinBlobs))
	}
	if m.QuotaMaxBlobs != 0 {
		n += 1 + sovParams(uint64(m.QuotaMaxBlobs))
	}
	if m.CreditCapBps != 0 {
		n += 2 + sovParams(uint64(m.CreditCapBps))
	}
	if m.EvictAfterMissedEpochs != 0 {
		n += 2 + sovParams(uint64(m.EvictAfterMissedEpochs))
	}
	if m.DealExtensionGraceBlocks != 0 {
		n += 2 + sovParams(uint64(m.DealExtensionGraceBlocks))
	}
	if m.VoucherMaxTtlBlocks != 0 {
		n += 2 + sovParams(uint64(m.VoucherMaxTtlBlocks))
	}
	if m.AuditBudgetBps != 0 {
		n += 2 + sovParams(uint64(m.AuditBudgetBps))
	}
	if m.AuditBudgetCapBps != 0 {
		n += 2 + sovParams(uint64(m.AuditBudgetCapBps))
	}
	if m.AuditBudgetCarryoverEpochs != 0 {
		n += 2 + sovParams(uint64(m.AuditBudgetCarryoverEpochs))
	}
	if m.EmissionStartHeight != 0 {
		n += 2 + sovParams(uint64(m.EmissionStartHeight))
	}
	if m.BaseRewardHalvingIntervalBlocks != 0 {
		n += 2 + sovParams(uint64(m.BaseRewardHalvingIntervalBlocks))
	}
	if m.BaseRewardBpsStart != 0 {
		n += 2 + sovParams(uint64(m.BaseRewardBpsStart))
	}
	if m.BaseRewardBpsTail != 0 {
		n += 2 + sovParams(uint64(m.BaseRewardBpsTail))
	}
	return n
}

func sovParams(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozParams(x uint64) (n int) {
	return sovParams(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *Params) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowParams
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: Params: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: Params: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field BaseStripeCost", wireType)
			}
			m.BaseStripeCost = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowParams
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.BaseStripeCost |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 2:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field HalvingInterval", wireType)
			}
			m.HalvingInterval = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowParams
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.HalvingInterval |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 3:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Eip712ChainId", wireType)
			}
			m.Eip712ChainId = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowParams
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Eip712ChainId |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 4:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field StoragePrice", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowParams
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthParams
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthParams
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.StoragePrice.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 5:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field DealCreationFee", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowParams
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthParams
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthParams
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.DealCreationFee.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 6:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field MinDurationBlocks", wireType)
			}
			m.MinDurationBlocks = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowParams
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.MinDurationBlocks |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 7:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field BaseRetrievalFee", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowParams
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthParams
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthParams
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.BaseRetrievalFee.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 8:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field RetrievalPricePerBlob", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowParams
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthParams
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthParams
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.RetrievalPricePerBlob.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 9:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field RetrievalBurnBps", wireType)
			}
			m.RetrievalBurnBps = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowParams
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.RetrievalBurnBps |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 10:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field MonthLenBlocks", wireType)
			}
			m.MonthLenBlocks = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowParams
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.MonthLenBlocks |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 11:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field EpochLenBlocks", wireType)
			}
			m.EpochLenBlocks = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowParams
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.EpochLenBlocks |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 12:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field QuotaBpsPerEpochHot", wireType)
			}
			m.QuotaBpsPerEpochHot = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowParams
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.QuotaBpsPerEpochHot |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 13:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field QuotaBpsPerEpochCold", wireType)
			}
			m.QuotaBpsPerEpochCold = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowParams
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.QuotaBpsPerEpochCold |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 14:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field QuotaMinBlobs", wireType)
			}
			m.QuotaMinBlobs = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowParams
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.QuotaMinBlobs |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 15:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field QuotaMaxBlobs", wireType)
			}
			m.QuotaMaxBlobs = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowParams
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.QuotaMaxBlobs |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 16:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field CreditCapBps", wireType)
			}
			m.CreditCapBps = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowParams
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.CreditCapBps |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 17:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field EvictAfterMissedEpochs", wireType)
			}
			m.EvictAfterMissedEpochs = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowParams
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.EvictAfterMissedEpochs |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 18:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field DealExtensionGraceBlocks", wireType)
			}
			m.DealExtensionGraceBlocks = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowParams
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.DealExtensionGraceBlocks |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 19:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field VoucherMaxTtlBlocks", wireType)
			}
			m.VoucherMaxTtlBlocks = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowParams
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.VoucherMaxTtlBlocks |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 20:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field AuditBudgetBps", wireType)
			}
			m.AuditBudgetBps = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowParams
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.AuditBudgetBps |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 21:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field AuditBudgetCapBps", wireType)
			}
			m.AuditBudgetCapBps = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowParams
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.AuditBudgetCapBps |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 22:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field AuditBudgetCarryoverEpochs", wireType)
			}
			m.AuditBudgetCarryoverEpochs = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowParams
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.AuditBudgetCarryoverEpochs |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 23:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field EmissionStartHeight", wireType)
			}
			m.EmissionStartHeight = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowParams
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.EmissionStartHeight |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 24:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field BaseRewardHalvingIntervalBlocks", wireType)
			}
			m.BaseRewardHalvingIntervalBlocks = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowParams
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.BaseRewardHalvingIntervalBlocks |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 25:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field BaseRewardBpsStart", wireType)
			}
			m.BaseRewardBpsStart = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowParams
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.BaseRewardBpsStart |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 26:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field BaseRewardBpsTail", wireType)
			}
			m.BaseRewardBpsTail = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowParams
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.BaseRewardBpsTail |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		default:
			iNdEx = preIndex
			skippy, err := skipParams(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthParams
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipParams(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowParams
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowParams
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowParams
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthParams
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupParams
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthParams
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthParams        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowParams          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupParams = fmt.Errorf("proto: unexpected end of group")
)
