// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: nilchain/nilchain/v1/params.proto

package types

import (
	cosmossdk_io_math "cosmossdk.io/math"
	fmt "fmt"
	types "github.com/cosmos/cosmos-sdk/types"
	_ "github.com/cosmos/cosmos-sdk/types/tx/amino"
	_ "github.com/cosmos/gogoproto/gogoproto"
	proto "github.com/cosmos/gogoproto/proto"
	io "io"
	math "math"
	math_bits "math/bits"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

// Params defines the parameters for the module.
type Params struct {
	BaseStripeCost        uint64                      `protobuf:"varint,1,opt,name=base_stripe_cost,json=baseStripeCost,proto3" json:"base_stripe_cost,omitempty"`
	HalvingInterval       uint64                      `protobuf:"varint,2,opt,name=halving_interval,json=halvingInterval,proto3" json:"halving_interval,omitempty"`
	Eip712ChainId         uint64                      `protobuf:"varint,3,opt,name=eip712_chain_id,json=eip712ChainId,proto3" json:"eip712_chain_id,omitempty"`
	StoragePrice          cosmossdk_io_math.LegacyDec `protobuf:"bytes,4,opt,name=storage_price,json=storagePrice,proto3,customtype=cosmossdk.io/math.LegacyDec" json:"storage_price"`
	DealCreationFee       types.Coin                  `protobuf:"bytes,5,opt,name=deal_creation_fee,json=dealCreationFee,proto3" json:"deal_creation_fee"`
	MinDurationBlocks     uint64                      `protobuf:"varint,6,opt,name=min_duration_blocks,json=minDurationBlocks,proto3" json:"min_duration_blocks,omitempty"`
	BaseRetrievalFee      types.Coin                  `protobuf:"bytes,7,opt,name=base_retrieval_fee,json=baseRetrievalFee,proto3" json:"base_retrieval_fee"`
	RetrievalPricePerBlob types.Coin                  `protobuf:"bytes,8,opt,name=retrieval_price_per_blob,json=retrievalPricePerBlob,proto3" json:"retrieval_price_per_blob"`
	RetrievalBurnBps      uint64                      `protobuf:"varint,9,opt,name=retrieval_burn_bps,json=retrievalBurnBps,proto3" json:"retrieval_burn_bps,omitempty"`
	// Length of the elasticity spend window ("month") in blocks.
	// When the chain height exceeds spend_window_start_height + month_len_blocks,
	// the window resets and spend_window_spent returns to 0.
	MonthLenBlocks uint64 `protobuf:"varint,10,opt,name=month_len_blocks,json=monthLenBlocks,proto3" json:"month_len_blocks,omitempty"`
}

func (m *Params) Reset()         { *m = Params{} }
func (m *Params) String() string { return proto.CompactTextString(m) }
func (*Params) ProtoMessage()    {}
func (*Params) Descriptor() ([]byte, []int) {
	return fileDescriptor_8ae414f9073848ab, []int{0}
}
func (m *Params) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *Params) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_Params.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *Params) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Params.Merge(m, src)
}
func (m *Params) XXX_Size() int {
	return m.Size()
}
func (m *Params) XXX_DiscardUnknown() {
	xxx_messageInfo_Params.DiscardUnknown(m)
}

var xxx_messageInfo_Params proto.InternalMessageInfo

func (m *Params) GetBaseStripeCost() uint64 {
	if m != nil {
		return m.BaseStripeCost
	}
	return 0
}

func (m *Params) GetHalvingInterval() uint64 {
	if m != nil {
		return m.HalvingInterval
	}
	return 0
}

func (m *Params) GetEip712ChainId() uint64 {
	if m != nil {
		return m.Eip712ChainId
	}
	return 0
}

func (m *Params) GetDealCreationFee() types.Coin {
	if m != nil {
		return m.DealCreationFee
	}
	return types.Coin{}
}

func (m *Params) GetMinDurationBlocks() uint64 {
	if m != nil {
		return m.MinDurationBlocks
	}
	return 0
}

func (m *Params) GetBaseRetrievalFee() types.Coin {
	if m != nil {
		return m.BaseRetrievalFee
	}
	return types.Coin{}
}

func (m *Params) GetRetrievalPricePerBlob() types.Coin {
	if m != nil {
		return m.RetrievalPricePerBlob
	}
	return types.Coin{}
}

func (m *Params) GetRetrievalBurnBps() uint64 {
	if m != nil {
		return m.RetrievalBurnBps
	}
	return 0
}

func (m *Params) GetMonthLenBlocks() uint64 {
	if m != nil {
		return m.MonthLenBlocks
	}
	return 0
}

func init() {
	proto.RegisterType((*Params)(nil), "nilchain.nilchain.v1.Params")
}

func init() { proto.RegisterFile("nilchain/nilchain/v1/params.proto", fileDescriptor_8ae414f9073848ab) }

var fileDescriptor_8ae414f9073848ab = []byte{
	// 507 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x8c, 0x52, 0xc1, 0x6e, 0xd3, 0x40,
	0x10, 0x8d, 0x21, 0x14, 0xba, 0x50, 0x92, 0x2c, 0x45, 0x72, 0x83, 0xe4, 0x04, 0x2a, 0xa1, 0x80,
	0x90, 0x2d, 0xb7, 0x07, 0x24, 0x8e, 0x4e, 0x85, 0xa8, 0x28, 0x52, 0x14, 0x2e, 0x88, 0xcb, 0x6a,
	0x6d, 0x0f, 0xce, 0xaa, 0xf6, 0xae, 0xb5, 0xbb, 0xb1, 0xe8, 0x2f, 0x70, 0xe2, 0x13, 0xf8, 0x04,
	0x3e, 0xa3, 0xc7, 0x1e, 0x11, 0x87, 0x0a, 0x25, 0x07, 0x38, 0xf3, 0x05, 0x68, 0xd7, 0xae, 0x73,
	0xe1, 0xd0, 0xcb, 0x6a, 0xf4, 0x66, 0xde, 0x9b, 0x9d, 0xa7, 0x87, 0x1e, 0x73, 0x96, 0x27, 0x0b,
	0xca, 0x78, 0xd0, 0x16, 0x55, 0x18, 0x94, 0x54, 0xd2, 0x42, 0xf9, 0xa5, 0x14, 0x5a, 0xe0, 0xdd,
	0xab, 0x8e, 0xdf, 0x16, 0x55, 0x38, 0x1c, 0xd0, 0x82, 0x71, 0x11, 0xd8, 0xb7, 0x1e, 0x1c, 0xee,
	0x66, 0x22, 0x13, 0xb6, 0x0c, 0x4c, 0xd5, 0xa0, 0x5e, 0x22, 0x54, 0x21, 0x54, 0x10, 0x53, 0x05,
	0x41, 0x15, 0xc6, 0xa0, 0x69, 0x18, 0x24, 0x82, 0xf1, 0xba, 0xff, 0xe4, 0x6f, 0x17, 0x6d, 0xcd,
	0xec, 0x3e, 0x3c, 0x41, 0x7d, 0x33, 0x45, 0x94, 0x96, 0xac, 0x04, 0x92, 0x08, 0xa5, 0x5d, 0x67,
	0xec, 0x4c, 0xba, 0xf3, 0xfb, 0x06, 0x7f, 0x6f, 0xe1, 0xa9, 0x50, 0x1a, 0x3f, 0x43, 0xfd, 0x05,
	0xcd, 0x2b, 0xc6, 0x33, 0xc2, 0xb8, 0x06, 0x59, 0xd1, 0xdc, 0xbd, 0x61, 0x27, 0x7b, 0x0d, 0x7e,
	0xdc, 0xc0, 0xf8, 0x29, 0xea, 0x01, 0x2b, 0x5f, 0x86, 0x07, 0xc4, 0xfe, 0x9d, 0xb0, 0xd4, 0xbd,
	0x69, 0x27, 0x77, 0x6a, 0x78, 0x6a, 0xd0, 0xe3, 0x14, 0xbf, 0x41, 0x3b, 0x4a, 0x0b, 0x49, 0x33,
	0x20, 0xa5, 0x64, 0x09, 0xb8, 0xdd, 0xb1, 0x33, 0xd9, 0x8e, 0xf6, 0xcf, 0x2f, 0x47, 0x9d, 0x9f,
	0x97, 0xa3, 0x47, 0xf5, 0x19, 0x2a, 0x3d, 0xf5, 0x99, 0x08, 0x0a, 0xaa, 0x17, 0xfe, 0x09, 0x64,
	0x34, 0x39, 0x3b, 0x82, 0x64, 0x7e, 0xaf, 0x61, 0xce, 0x0c, 0x11, 0xbf, 0x45, 0x83, 0x14, 0x68,
	0x4e, 0x12, 0x09, 0x54, 0x33, 0xc1, 0xc9, 0x27, 0x00, 0xf7, 0xd6, 0xd8, 0x99, 0xdc, 0x3d, 0xd8,
	0xf3, 0x6b, 0x19, 0xdf, 0xdc, 0xe3, 0x37, 0x6e, 0xf8, 0x53, 0xc1, 0x78, 0xd4, 0x35, 0x8b, 0xe6,
	0x3d, 0xc3, 0x9c, 0x36, 0xc4, 0xd7, 0x00, 0xd8, 0x47, 0x0f, 0x0a, 0xc6, 0x49, 0xba, 0x94, 0xb5,
	0x56, 0x9c, 0x8b, 0xe4, 0x54, 0xb9, 0x5b, 0xf6, 0x84, 0x41, 0xc1, 0xf8, 0x51, 0xd3, 0x89, 0x6c,
	0x03, 0xbf, 0x43, 0xd8, 0x7a, 0x28, 0x41, 0x4b, 0x06, 0x15, 0xcd, 0xed, 0xf6, 0xdb, 0xd7, 0xdb,
	0x6e, 0xed, 0x9f, 0x5f, 0x31, 0xcd, 0xfa, 0x0f, 0xc8, 0xdd, 0x28, 0x59, 0x5f, 0x48, 0x09, 0xd2,
	0xfc, 0x22, 0x76, 0xef, 0x5c, 0x4f, 0xf4, 0x61, 0x2b, 0x60, 0xed, 0x99, 0x81, 0x8c, 0x72, 0x11,
	0xe3, 0x17, 0x08, 0x6f, 0x94, 0xe3, 0xa5, 0xe4, 0x24, 0x2e, 0x95, 0xbb, 0x6d, 0xef, 0xea, 0xb7,
	0x9d, 0x68, 0x29, 0x79, 0x54, 0xda, 0x68, 0x14, 0x82, 0xeb, 0x05, 0xc9, 0xa1, 0xf5, 0x00, 0xd5,
	0xd1, 0xb0, 0xf8, 0x09, 0x34, 0x06, 0xbc, 0xda, 0xff, 0xf3, 0x6d, 0xe4, 0x7c, 0xf9, 0xfd, 0xfd,
	0xf9, 0xb0, 0x4d, 0xf4, 0xe7, 0x4d, 0xb8, 0xeb, 0xa4, 0x45, 0x87, 0xe7, 0x2b, 0xcf, 0xb9, 0x58,
	0x79, 0xce, 0xaf, 0x95, 0xe7, 0x7c, 0x5d, 0x7b, 0x9d, 0x8b, 0xb5, 0xd7, 0xf9, 0xb1, 0xf6, 0x3a,
	0x1f, 0xf7, 0xfe, 0xc7, 0xd2, 0x67, 0x25, 0xa8, 0x78, 0xcb, 0x06, 0xf6, 0xf0, 0x5f, 0x00, 0x00,
	0x00, 0xff, 0xff, 0xfa, 0xc0, 0x3b, 0x06, 0x34, 0x03, 0x00, 0x00,
}

func (this *Params) Equal(that interface{}) bool {
	if that == nil {
		return this == nil
	}

	that1, ok := that.(*Params)
	if !ok {
		that2, ok := that.(Params)
		if ok {
			that1 = &that2
		} else {
			return false
		}
	}
	if that1 == nil {
		return this == nil
	} else if this == nil {
		return false
	}
	if this.BaseStripeCost != that1.BaseStripeCost {
		return false
	}
	if this.HalvingInterval != that1.HalvingInterval {
		return false
	}
	if this.Eip712ChainId != that1.Eip712ChainId {
		return false
	}
	if !this.StoragePrice.Equal(that1.StoragePrice) {
		return false
	}
	if !this.DealCreationFee.Equal(&that1.DealCreationFee) {
		return false
	}
	if this.MinDurationBlocks != that1.MinDurationBlocks {
		return false
	}
	if !this.BaseRetrievalFee.Equal(&that1.BaseRetrievalFee) {
		return false
	}
	if !this.RetrievalPricePerBlob.Equal(&that1.RetrievalPricePerBlob) {
		return false
	}
	if this.RetrievalBurnBps != that1.RetrievalBurnBps {
		return false
	}
	if this.MonthLenBlocks != that1.MonthLenBlocks {
		return false
	}
	return true
}
func (m *Params) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *Params) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *Params) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.MonthLenBlocks != 0 {
		i = encodeVarintParams(dAtA, i, uint64(m.MonthLenBlocks))
		i--
		dAtA[i] = 0x50
	}
	if m.RetrievalBurnBps != 0 {
		i = encodeVarintParams(dAtA, i, uint64(m.RetrievalBurnBps))
		i--
		dAtA[i] = 0x48
	}
	{
		size, err := m.RetrievalPricePerBlob.MarshalToSizedBuffer(dAtA[:i])
		if err != nil {
			return 0, err
		}
		i -= size
		i = encodeVarintParams(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0x42
	{
		size, err := m.BaseRetrievalFee.MarshalToSizedBuffer(dAtA[:i])
		if err != nil {
			return 0, err
		}
		i -= size
		i = encodeVarintParams(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0x3a
	if m.MinDurationBlocks != 0 {
		i = encodeVarintParams(dAtA, i, uint64(m.MinDurationBlocks))
		i--
		dAtA[i] = 0x30
	}
	{
		size, err := m.DealCreationFee.MarshalToSizedBuffer(dAtA[:i])
		if err != nil {
			return 0, err
		}
		i -= size
		i = encodeVarintParams(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0x2a
	{
		size := m.StoragePrice.Size()
		i -= size
		if _, err := m.StoragePrice.MarshalTo(dAtA[i:]); err != nil {
			return 0, err
		}
		i = encodeVarintParams(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0x22
	if m.Eip712ChainId != 0 {
		i = encodeVarintParams(dAtA, i, uint64(m.Eip712ChainId))
		i--
		dAtA[i] = 0x18
	}
	if m.HalvingInterval != 0 {
		i = encodeVarintParams(dAtA, i, uint64(m.HalvingInterval))
		i--
		dAtA[i] = 0x10
	}
	if m.BaseStripeCost != 0 {
		i = encodeVarintParams(dAtA, i, uint64(m.BaseStripeCost))
		i--
		dAtA[i] = 0x8
	}
	return len(dAtA) - i, nil
}

func encodeVarintParams(dAtA []byte, offset int, v uint64) int {
	offset -= sovParams(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *Params) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.BaseStripeCost != 0 {
		n += 1 + sovParams(uint64(m.BaseStripeCost))
	}
	if m.HalvingInterval != 0 {
		n += 1 + sovParams(uint64(m.HalvingInterval))
	}
	if m.Eip712ChainId != 0 {
		n += 1 + sovParams(uint64(m.Eip712ChainId))
	}
	l = m.StoragePrice.Size()
	n += 1 + l + sovParams(uint64(l))
	l = m.DealCreationFee.Size()
	n += 1 + l + sovParams(uint64(l))
	if m.MinDurationBlocks != 0 {
		n += 1 + sovParams(uint64(m.MinDurationBlocks))
	}
	l = m.BaseRetrievalFee.Size()
	n += 1 + l + sovParams(uint64(l))
	l = m.RetrievalPricePerBlob.Size()
	n += 1 + l + sovParams(uint64(l))
	if m.RetrievalBurnBps != 0 {
		n += 1 + sovParams(uint64(m.RetrievalBurnBps))
	}
	if m.MonthLenBlocks != 0 {
		n += 1 + sovParams(uint64(m.MonthLenBlocks))
	}
	return n
}

func sovParams(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozParams(x uint64) (n int) {
	return sovParams(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *Params) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowParams
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: Params: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: Params: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field BaseStripeCost", wireType)
			}
			m.BaseStripeCost = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowParams
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.BaseStripeCost |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 2:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field HalvingInterval", wireType)
			}
			m.HalvingInterval = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowParams
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.HalvingInterval |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 3:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Eip712ChainId", wireType)
			}
			m.Eip712ChainId = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowParams
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Eip712ChainId |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 4:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field StoragePrice", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowParams
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthParams
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthParams
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.StoragePrice.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 5:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field DealCreationFee", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowParams
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthParams
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthParams
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.DealCreationFee.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 6:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field MinDurationBlocks", wireType)
			}
			m.MinDurationBlocks = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowParams
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.MinDurationBlocks |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 7:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field BaseRetrievalFee", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowParams
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthParams
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthParams
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.BaseRetrievalFee.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 8:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field RetrievalPricePerBlob", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowParams
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthParams
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthParams
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.RetrievalPricePerBlob.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 9:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field RetrievalBurnBps", wireType)
			}
			m.RetrievalBurnBps = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowParams
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.RetrievalBurnBps |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 10:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field MonthLenBlocks", wireType)
			}
			m.MonthLenBlocks = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowParams
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.MonthLenBlocks |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		default:
			iNdEx = preIndex
			skippy, err := skipParams(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthParams
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipParams(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowParams
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowParams
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowParams
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthParams
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupParams
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthParams
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthParams        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowParams          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupParams = fmt.Errorf("proto: unexpected end of group")
)
