// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: nilchain/nilchain/v1/tx.proto

package types

import (
	context "context"
	cosmossdk_io_math "cosmossdk.io/math"
	fmt "fmt"
	_ "github.com/cosmos/cosmos-proto"
	_ "github.com/cosmos/cosmos-sdk/types/msgservice"
	_ "github.com/cosmos/cosmos-sdk/types/tx/amino"
	_ "github.com/cosmos/gogoproto/gogoproto"
	grpc1 "github.com/cosmos/gogoproto/grpc"
	proto "github.com/cosmos/gogoproto/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	io "io"
	math "math"
	math_bits "math/bits"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

// MsgUpdateParams is the Msg/UpdateParams request type.
type MsgUpdateParams struct {
	// authority is the address that controls the module (defaults to x/gov unless overwritten).
	Authority string `protobuf:"bytes,1,opt,name=authority,proto3" json:"authority,omitempty"`
	// params defines the module parameters to update.
	//
	// NOTE: All parameters must be supplied.
	Params Params `protobuf:"bytes,2,opt,name=params,proto3" json:"params"`
}

func (m *MsgUpdateParams) Reset()         { *m = MsgUpdateParams{} }
func (m *MsgUpdateParams) String() string { return proto.CompactTextString(m) }
func (*MsgUpdateParams) ProtoMessage()    {}
func (*MsgUpdateParams) Descriptor() ([]byte, []int) {
	return fileDescriptor_48ebc739066bad25, []int{0}
}
func (m *MsgUpdateParams) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *MsgUpdateParams) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_MsgUpdateParams.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *MsgUpdateParams) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgUpdateParams.Merge(m, src)
}
func (m *MsgUpdateParams) XXX_Size() int {
	return m.Size()
}
func (m *MsgUpdateParams) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgUpdateParams.DiscardUnknown(m)
}

var xxx_messageInfo_MsgUpdateParams proto.InternalMessageInfo

func (m *MsgUpdateParams) GetAuthority() string {
	if m != nil {
		return m.Authority
	}
	return ""
}

func (m *MsgUpdateParams) GetParams() Params {
	if m != nil {
		return m.Params
	}
	return Params{}
}

// MsgUpdateParamsResponse defines the response structure for executing a
// MsgUpdateParams message.
type MsgUpdateParamsResponse struct {
}

func (m *MsgUpdateParamsResponse) Reset()         { *m = MsgUpdateParamsResponse{} }
func (m *MsgUpdateParamsResponse) String() string { return proto.CompactTextString(m) }
func (*MsgUpdateParamsResponse) ProtoMessage()    {}
func (*MsgUpdateParamsResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_48ebc739066bad25, []int{1}
}
func (m *MsgUpdateParamsResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *MsgUpdateParamsResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_MsgUpdateParamsResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *MsgUpdateParamsResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgUpdateParamsResponse.Merge(m, src)
}
func (m *MsgUpdateParamsResponse) XXX_Size() int {
	return m.Size()
}
func (m *MsgUpdateParamsResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgUpdateParamsResponse.DiscardUnknown(m)
}

var xxx_messageInfo_MsgUpdateParamsResponse proto.InternalMessageInfo

// MsgRegisterProvider allows a Storage Provider to register themselves with the network.
type MsgRegisterProvider struct {
	Creator      string `protobuf:"bytes,1,opt,name=creator,proto3" json:"creator,omitempty"`
	Capabilities string `protobuf:"bytes,2,opt,name=capabilities,proto3" json:"capabilities,omitempty"`
	TotalStorage uint64 `protobuf:"varint,3,opt,name=total_storage,json=totalStorage,proto3" json:"total_storage,omitempty"`
}

func (m *MsgRegisterProvider) Reset()         { *m = MsgRegisterProvider{} }
func (m *MsgRegisterProvider) String() string { return proto.CompactTextString(m) }
func (*MsgRegisterProvider) ProtoMessage()    {}
func (*MsgRegisterProvider) Descriptor() ([]byte, []int) {
	return fileDescriptor_48ebc739066bad25, []int{2}
}
func (m *MsgRegisterProvider) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *MsgRegisterProvider) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_MsgRegisterProvider.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *MsgRegisterProvider) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgRegisterProvider.Merge(m, src)
}
func (m *MsgRegisterProvider) XXX_Size() int {
	return m.Size()
}
func (m *MsgRegisterProvider) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgRegisterProvider.DiscardUnknown(m)
}

var xxx_messageInfo_MsgRegisterProvider proto.InternalMessageInfo

func (m *MsgRegisterProvider) GetCreator() string {
	if m != nil {
		return m.Creator
	}
	return ""
}

func (m *MsgRegisterProvider) GetCapabilities() string {
	if m != nil {
		return m.Capabilities
	}
	return ""
}

func (m *MsgRegisterProvider) GetTotalStorage() uint64 {
	if m != nil {
		return m.TotalStorage
	}
	return 0
}

// MsgRegisterProviderResponse defines the response structure for registering a provider.
type MsgRegisterProviderResponse struct {
	Success bool `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
}

func (m *MsgRegisterProviderResponse) Reset()         { *m = MsgRegisterProviderResponse{} }
func (m *MsgRegisterProviderResponse) String() string { return proto.CompactTextString(m) }
func (*MsgRegisterProviderResponse) ProtoMessage()    {}
func (*MsgRegisterProviderResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_48ebc739066bad25, []int{3}
}
func (m *MsgRegisterProviderResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *MsgRegisterProviderResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_MsgRegisterProviderResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *MsgRegisterProviderResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgRegisterProviderResponse.Merge(m, src)
}
func (m *MsgRegisterProviderResponse) XXX_Size() int {
	return m.Size()
}
func (m *MsgRegisterProviderResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgRegisterProviderResponse.DiscardUnknown(m)
}

var xxx_messageInfo_MsgRegisterProviderResponse proto.InternalMessageInfo

func (m *MsgRegisterProviderResponse) GetSuccess() bool {
	if m != nil {
		return m.Success
	}
	return false
}

// MsgCreateDeal allows a user to create a new storage deal.
type MsgCreateDeal struct {
	Creator             string                `protobuf:"bytes,1,opt,name=creator,proto3" json:"creator,omitempty"`
	Cid                 string                `protobuf:"bytes,2,opt,name=cid,proto3" json:"cid,omitempty"`
	Size_               uint64                `protobuf:"varint,3,opt,name=size,proto3" json:"size,omitempty"`
	DurationBlocks      uint64                `protobuf:"varint,4,opt,name=duration_blocks,json=durationBlocks,proto3" json:"duration_blocks,omitempty"`
	ServiceHint         string                `protobuf:"bytes,5,opt,name=service_hint,json=serviceHint,proto3" json:"service_hint,omitempty"`
	MaxMonthlySpend     cosmossdk_io_math.Int `protobuf:"bytes,6,opt,name=max_monthly_spend,json=maxMonthlySpend,proto3,customtype=cosmossdk.io/math.Int" json:"max_monthly_spend"`
	InitialEscrowAmount cosmossdk_io_math.Int `protobuf:"bytes,7,opt,name=initial_escrow_amount,json=initialEscrowAmount,proto3,customtype=cosmossdk.io/math.Int" json:"initial_escrow_amount"`
}

func (m *MsgCreateDeal) Reset()         { *m = MsgCreateDeal{} }
func (m *MsgCreateDeal) String() string { return proto.CompactTextString(m) }
func (*MsgCreateDeal) ProtoMessage()    {}
func (*MsgCreateDeal) Descriptor() ([]byte, []int) {
	return fileDescriptor_48ebc739066bad25, []int{4}
}
func (m *MsgCreateDeal) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *MsgCreateDeal) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_MsgCreateDeal.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *MsgCreateDeal) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgCreateDeal.Merge(m, src)
}
func (m *MsgCreateDeal) XXX_Size() int {
	return m.Size()
}
func (m *MsgCreateDeal) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgCreateDeal.DiscardUnknown(m)
}

var xxx_messageInfo_MsgCreateDeal proto.InternalMessageInfo

func (m *MsgCreateDeal) GetCreator() string {
	if m != nil {
		return m.Creator
	}
	return ""
}

func (m *MsgCreateDeal) GetCid() string {
	if m != nil {
		return m.Cid
	}
	return ""
}

func (m *MsgCreateDeal) GetSize_() uint64 {
	if m != nil {
		return m.Size_
	}
	return 0
}

func (m *MsgCreateDeal) GetDurationBlocks() uint64 {
	if m != nil {
		return m.DurationBlocks
	}
	return 0
}

func (m *MsgCreateDeal) GetServiceHint() string {
	if m != nil {
		return m.ServiceHint
	}
	return ""
}

// MsgCreateDealResponse defines the response structure for creating a deal.
type MsgCreateDealResponse struct {
	DealId            uint64   `protobuf:"varint,1,opt,name=deal_id,json=dealId,proto3" json:"deal_id,omitempty"`
	AssignedProviders []string `protobuf:"bytes,2,rep,name=assigned_providers,json=assignedProviders,proto3" json:"assigned_providers,omitempty"`
}

func (m *MsgCreateDealResponse) Reset()         { *m = MsgCreateDealResponse{} }
func (m *MsgCreateDealResponse) String() string { return proto.CompactTextString(m) }
func (*MsgCreateDealResponse) ProtoMessage()    {}
func (*MsgCreateDealResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_48ebc739066bad25, []int{5}
}
func (m *MsgCreateDealResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *MsgCreateDealResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_MsgCreateDealResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *MsgCreateDealResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgCreateDealResponse.Merge(m, src)
}
func (m *MsgCreateDealResponse) XXX_Size() int {
	return m.Size()
}
func (m *MsgCreateDealResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgCreateDealResponse.DiscardUnknown(m)
}

var xxx_messageInfo_MsgCreateDealResponse proto.InternalMessageInfo

func (m *MsgCreateDealResponse) GetDealId() uint64 {
	if m != nil {
		return m.DealId
	}
	return 0
}

func (m *MsgCreateDealResponse) GetAssignedProviders() []string {
	if m != nil {
		return m.AssignedProviders
	}
	return nil
}

// MsgProveLiveness allows a Storage Provider to submit a proof of data liveness.
type MsgProveLiveness struct {
	Creator string `protobuf:"bytes,1,opt,name=creator,proto3" json:"creator,omitempty"`
	DealId  uint64 `protobuf:"varint,2,opt,name=deal_id,json=dealId,proto3" json:"deal_id,omitempty"`
	EpochId uint64 `protobuf:"varint,3,opt,name=epoch_id,json=epochId,proto3" json:"epoch_id,omitempty"`
	// Types that are valid to be assigned to ProofType:
	//	*MsgProveLiveness_UserReceipt
	//	*MsgProveLiveness_SystemProof
	ProofType isMsgProveLiveness_ProofType `protobuf_oneof:"proof_type"`
}

func (m *MsgProveLiveness) Reset()         { *m = MsgProveLiveness{} }
func (m *MsgProveLiveness) String() string { return proto.CompactTextString(m) }
func (*MsgProveLiveness) ProtoMessage()    {}
func (*MsgProveLiveness) Descriptor() ([]byte, []int) {
	return fileDescriptor_48ebc739066bad25, []int{6}
}
func (m *MsgProveLiveness) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *MsgProveLiveness) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_MsgProveLiveness.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *MsgProveLiveness) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgProveLiveness.Merge(m, src)
}
func (m *MsgProveLiveness) XXX_Size() int {
	return m.Size()
}
func (m *MsgProveLiveness) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgProveLiveness.DiscardUnknown(m)
}

var xxx_messageInfo_MsgProveLiveness proto.InternalMessageInfo

type isMsgProveLiveness_ProofType interface {
	isMsgProveLiveness_ProofType()
	MarshalTo([]byte) (int, error)
	Size() int
}

type MsgProveLiveness_UserReceipt struct {
	UserReceipt *RetrievalReceipt `protobuf:"bytes,4,opt,name=user_receipt,json=userReceipt,proto3,oneof" json:"user_receipt,omitempty"`
}
type MsgProveLiveness_SystemProof struct {
	SystemProof *KzgProof `protobuf:"bytes,5,opt,name=system_proof,json=systemProof,proto3,oneof" json:"system_proof,omitempty"`
}

func (*MsgProveLiveness_UserReceipt) isMsgProveLiveness_ProofType() {}
func (*MsgProveLiveness_SystemProof) isMsgProveLiveness_ProofType() {}

func (m *MsgProveLiveness) GetProofType() isMsgProveLiveness_ProofType {
	if m != nil {
		return m.ProofType
	}
	return nil
}

func (m *MsgProveLiveness) GetCreator() string {
	if m != nil {
		return m.Creator
	}
	return ""
}

func (m *MsgProveLiveness) GetDealId() uint64 {
	if m != nil {
		return m.DealId
	}
	return 0
}

func (m *MsgProveLiveness) GetEpochId() uint64 {
	if m != nil {
		return m.EpochId
	}
	return 0
}

func (m *MsgProveLiveness) GetUserReceipt() *RetrievalReceipt {
	if x, ok := m.GetProofType().(*MsgProveLiveness_UserReceipt); ok {
		return x.UserReceipt
	}
	return nil
}

func (m *MsgProveLiveness) GetSystemProof() *KzgProof {
	if x, ok := m.GetProofType().(*MsgProveLiveness_SystemProof); ok {
		return x.SystemProof
	}
	return nil
}

// XXX_OneofWrappers is for the internal use of the proto package.
func (*MsgProveLiveness) XXX_OneofWrappers() []interface{} {
	return []interface{}{
		(*MsgProveLiveness_UserReceipt)(nil),
		(*MsgProveLiveness_SystemProof)(nil),
	}
}

// MsgProveLivenessResponse defines the response structure for proving liveness.
type MsgProveLivenessResponse struct {
	Success      bool   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Tier         uint32 `protobuf:"varint,2,opt,name=tier,proto3" json:"tier,omitempty"`
	RewardAmount string `protobuf:"bytes,3,opt,name=reward_amount,json=rewardAmount,proto3" json:"reward_amount,omitempty"`
}

func (m *MsgProveLivenessResponse) Reset()         { *m = MsgProveLivenessResponse{} }
func (m *MsgProveLivenessResponse) String() string { return proto.CompactTextString(m) }
func (*MsgProveLivenessResponse) ProtoMessage()    {}
func (*MsgProveLivenessResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_48ebc739066bad25, []int{7}
}
func (m *MsgProveLivenessResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *MsgProveLivenessResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_MsgProveLivenessResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *MsgProveLivenessResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgProveLivenessResponse.Merge(m, src)
}
func (m *MsgProveLivenessResponse) XXX_Size() int {
	return m.Size()
}
func (m *MsgProveLivenessResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgProveLivenessResponse.DiscardUnknown(m)
}

var xxx_messageInfo_MsgProveLivenessResponse proto.InternalMessageInfo

func (m *MsgProveLivenessResponse) GetSuccess() bool {
	if m != nil {
		return m.Success
	}
	return false
}

func (m *MsgProveLivenessResponse) GetTier() uint32 {
	if m != nil {
		return m.Tier
	}
	return 0
}

func (m *MsgProveLivenessResponse) GetRewardAmount() string {
	if m != nil {
		return m.RewardAmount
	}
	return ""
}

// MsgSignalSaturation allows a Storage Provider to signal high load for a deal.
type MsgSignalSaturation struct {
	Creator string `protobuf:"bytes,1,opt,name=creator,proto3" json:"creator,omitempty"`
	DealId  uint64 `protobuf:"varint,2,opt,name=deal_id,json=dealId,proto3" json:"deal_id,omitempty"`
}

func (m *MsgSignalSaturation) Reset()         { *m = MsgSignalSaturation{} }
func (m *MsgSignalSaturation) String() string { return proto.CompactTextString(m) }
func (*MsgSignalSaturation) ProtoMessage()    {}
func (*MsgSignalSaturation) Descriptor() ([]byte, []int) {
	return fileDescriptor_48ebc739066bad25, []int{8}
}
func (m *MsgSignalSaturation) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *MsgSignalSaturation) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_MsgSignalSaturation.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *MsgSignalSaturation) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgSignalSaturation.Merge(m, src)
}
func (m *MsgSignalSaturation) XXX_Size() int {
	return m.Size()
}
func (m *MsgSignalSaturation) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgSignalSaturation.DiscardUnknown(m)
}

var xxx_messageInfo_MsgSignalSaturation proto.InternalMessageInfo

func (m *MsgSignalSaturation) GetCreator() string {
	if m != nil {
		return m.Creator
	}
	return ""
}

func (m *MsgSignalSaturation) GetDealId() uint64 {
	if m != nil {
		return m.DealId
	}
	return 0
}

// MsgSignalSaturationResponse defines the response structure for signaling saturation.
type MsgSignalSaturationResponse struct {
	Success      bool     `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message      string   `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	NewProviders []string `protobuf:"bytes,3,rep,name=new_providers,json=newProviders,proto3" json:"new_providers,omitempty"`
}

func (m *MsgSignalSaturationResponse) Reset()         { *m = MsgSignalSaturationResponse{} }
func (m *MsgSignalSaturationResponse) String() string { return proto.CompactTextString(m) }
func (*MsgSignalSaturationResponse) ProtoMessage()    {}
func (*MsgSignalSaturationResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_48ebc739066bad25, []int{9}
}
func (m *MsgSignalSaturationResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *MsgSignalSaturationResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_MsgSignalSaturationResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *MsgSignalSaturationResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgSignalSaturationResponse.Merge(m, src)
}
func (m *MsgSignalSaturationResponse) XXX_Size() int {
	return m.Size()
}
func (m *MsgSignalSaturationResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgSignalSaturationResponse.DiscardUnknown(m)
}

var xxx_messageInfo_MsgSignalSaturationResponse proto.InternalMessageInfo

func (m *MsgSignalSaturationResponse) GetSuccess() bool {
	if m != nil {
		return m.Success
	}
	return false
}

func (m *MsgSignalSaturationResponse) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

func (m *MsgSignalSaturationResponse) GetNewProviders() []string {
	if m != nil {
		return m.NewProviders
	}
	return nil
}

func init() {
	proto.RegisterType((*MsgUpdateParams)(nil), "nilchain.nilchain.v1.MsgUpdateParams")
	proto.RegisterType((*MsgUpdateParamsResponse)(nil), "nilchain.nilchain.v1.MsgUpdateParamsResponse")
	proto.RegisterType((*MsgRegisterProvider)(nil), "nilchain.nilchain.v1.MsgRegisterProvider")
	proto.RegisterType((*MsgRegisterProviderResponse)(nil), "nilchain.nilchain.v1.MsgRegisterProviderResponse")
	proto.RegisterType((*MsgCreateDeal)(nil), "nilchain.nilchain.v1.MsgCreateDeal")
	proto.RegisterType((*MsgCreateDealResponse)(nil), "nilchain.nilchain.v1.MsgCreateDealResponse")
	proto.RegisterType((*MsgProveLiveness)(nil), "nilchain.nilchain.v1.MsgProveLiveness")
	proto.RegisterType((*MsgProveLivenessResponse)(nil), "nilchain.nilchain.v1.MsgProveLivenessResponse")
	proto.RegisterType((*MsgSignalSaturation)(nil), "nilchain.nilchain.v1.MsgSignalSaturation")
	proto.RegisterType((*MsgSignalSaturationResponse)(nil), "nilchain.nilchain.v1.MsgSignalSaturationResponse")
}

func init() { proto.RegisterFile("nilchain/nilchain/v1/tx.proto", fileDescriptor_48ebc739066bad25) }

var fileDescriptor_48ebc739066bad25 = []byte{
	// 974 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xac, 0x56, 0x4f, 0x6f, 0x1b, 0x45,
	0x14, 0xcf, 0xc6, 0x6e, 0xdc, 0x3c, 0xdb, 0x24, 0x99, 0x26, 0xca, 0xc6, 0x50, 0x37, 0xd9, 0x40,
	0x1b, 0x82, 0x6a, 0x2b, 0xae, 0x28, 0x28, 0x12, 0x42, 0x75, 0x41, 0x34, 0x2a, 0x96, 0xca, 0x5a,
	0x5c, 0x38, 0xb0, 0x9a, 0xec, 0x4e, 0xd7, 0xa3, 0x7a, 0x77, 0x56, 0x33, 0x63, 0x27, 0xee, 0x09,
	0x71, 0x41, 0xe2, 0xd4, 0x0f, 0x80, 0xc4, 0x95, 0x63, 0x0e, 0x7c, 0x02, 0x4e, 0x3d, 0x70, 0x28,
	0x9c, 0x10, 0x87, 0x0a, 0x25, 0x87, 0x7c, 0x0d, 0x34, 0xb3, 0xbb, 0x76, 0xbc, 0xb5, 0x1b, 0xab,
	0xea, 0x65, 0x35, 0xf3, 0x9b, 0xdf, 0x7b, 0xf3, 0xfe, 0xfc, 0xf6, 0xed, 0xc2, 0xf5, 0x90, 0x76,
	0xdd, 0x0e, 0xa6, 0x61, 0x7d, 0xb8, 0xe8, 0xef, 0xd5, 0xe5, 0x71, 0x2d, 0xe2, 0x4c, 0x32, 0xb4,
	0x9a, 0xa2, 0xb5, 0xe1, 0xa2, 0xbf, 0x57, 0x59, 0xc1, 0x01, 0x0d, 0x59, 0x5d, 0x3f, 0x63, 0x62,
	0x65, 0xdd, 0x65, 0x22, 0x60, 0xa2, 0x1e, 0x08, 0x5f, 0x39, 0x08, 0x84, 0x9f, 0x1c, 0x6c, 0xc4,
	0x07, 0x8e, 0xde, 0xd5, 0xe3, 0x4d, 0x72, 0xb4, 0xea, 0x33, 0x9f, 0xc5, 0xb8, 0x5a, 0x25, 0xe8,
	0xd6, 0xc4, 0x88, 0x22, 0xcc, 0x71, 0x90, 0x1a, 0x6e, 0x4e, 0x0e, 0x7a, 0x10, 0x91, 0x84, 0x61,
	0xfd, 0x61, 0xc0, 0x52, 0x4b, 0xf8, 0xdf, 0x46, 0x1e, 0x96, 0xe4, 0x91, 0xb6, 0x45, 0x77, 0x61,
	0x11, 0xf7, 0x64, 0x87, 0x71, 0x2a, 0x07, 0xa6, 0xb1, 0x69, 0xec, 0x2c, 0x36, 0xcd, 0xbf, 0x7f,
	0xbf, 0xbd, 0x9a, 0xc4, 0x74, 0xcf, 0xf3, 0x38, 0x11, 0xa2, 0x2d, 0x39, 0x0d, 0x7d, 0x7b, 0x44,
	0x45, 0x9f, 0xc3, 0x42, 0x7c, 0xbb, 0x39, 0xbf, 0x69, 0xec, 0x14, 0x1b, 0xef, 0xd5, 0x26, 0x15,
	0xa5, 0x16, 0xdf, 0xd2, 0x5c, 0x7c, 0xfe, 0xf2, 0xc6, 0xdc, 0x6f, 0xe7, 0x27, 0xbb, 0x86, 0x9d,
	0x98, 0xed, 0xdf, 0xfd, 0xf1, 0xfc, 0x64, 0x77, 0xe4, 0xf0, 0xe7, 0xf3, 0x93, 0xdd, 0xed, 0x61,
	0xe0, 0xc7, 0xa3, 0x1c, 0x32, 0x01, 0x5b, 0x1b, 0xb0, 0x9e, 0x81, 0x6c, 0x22, 0x22, 0x16, 0x0a,
	0x62, 0xfd, 0x69, 0xc0, 0xb5, 0x96, 0xf0, 0x6d, 0xe2, 0x53, 0x21, 0x09, 0x7f, 0xc4, 0x59, 0x9f,
	0x7a, 0x84, 0xa3, 0x06, 0x14, 0x5c, 0x4e, 0xb0, 0x64, 0xfc, 0xd2, 0x0c, 0x53, 0x22, 0xb2, 0xa0,
	0xe4, 0xe2, 0x08, 0x1f, 0xd2, 0x2e, 0x95, 0x94, 0xc4, 0x59, 0x2e, 0xda, 0x63, 0x18, 0xda, 0x86,
	0xb2, 0x64, 0x12, 0x77, 0x1d, 0x21, 0x19, 0xc7, 0x3e, 0x31, 0x73, 0x9b, 0xc6, 0x4e, 0xde, 0x2e,
	0x69, 0xb0, 0x1d, 0x63, 0xfb, 0x9f, 0xaa, 0x3c, 0x53, 0xb7, 0x2a, 0xcb, 0x5b, 0x53, 0xb2, 0xcc,
	0x86, 0x6d, 0x7d, 0x02, 0xef, 0x4e, 0x80, 0xd3, 0x6c, 0x91, 0x09, 0x05, 0xd1, 0x73, 0x5d, 0x22,
	0x84, 0xce, 0xea, 0xaa, 0x9d, 0x6e, 0xad, 0x9f, 0x72, 0x50, 0x6e, 0x09, 0xff, 0xbe, 0xba, 0x93,
	0x7c, 0x41, 0x70, 0xf7, 0x8d, 0x2a, 0xb0, 0x0c, 0x39, 0x97, 0x7a, 0x49, 0xe2, 0x6a, 0x89, 0x10,
	0xe4, 0x05, 0x7d, 0x9a, 0xa6, 0xa9, 0xd7, 0xe8, 0x16, 0x2c, 0x79, 0x3d, 0x8e, 0x25, 0x65, 0xa1,
	0x73, 0xd8, 0x65, 0xee, 0x13, 0x61, 0xe6, 0xf5, 0xf1, 0x3b, 0x29, 0xdc, 0xd4, 0x28, 0xda, 0x82,
	0x92, 0x20, 0xbc, 0x4f, 0x5d, 0xe2, 0x74, 0x68, 0x28, 0xcd, 0x2b, 0xda, 0x6f, 0x31, 0xc1, 0x1e,
	0xd0, 0x50, 0xa2, 0x03, 0x58, 0x09, 0xf0, 0xb1, 0x13, 0xb0, 0x50, 0x76, 0xba, 0x03, 0x47, 0x44,
	0x24, 0xf4, 0xcc, 0x05, 0x1d, 0xef, 0x75, 0x25, 0xa0, 0x7f, 0x5f, 0xde, 0x58, 0x8b, 0x63, 0x16,
	0xde, 0x93, 0x1a, 0x65, 0xf5, 0x00, 0xcb, 0x4e, 0xed, 0x20, 0x94, 0xf6, 0x52, 0x80, 0x8f, 0x5b,
	0xb1, 0x59, 0x5b, 0x59, 0xa1, 0x6f, 0x60, 0x8d, 0x86, 0x54, 0x52, 0xdc, 0x75, 0x88, 0x70, 0x39,
	0x3b, 0x72, 0x70, 0xc0, 0x7a, 0xa1, 0x34, 0x0b, 0xb3, 0xb8, 0xbb, 0x96, 0xd8, 0x7e, 0xa9, 0x4d,
	0xef, 0x69, 0xcb, 0xfd, 0x46, 0xb6, 0x91, 0x5b, 0x53, 0x1a, 0x39, 0xaa, 0xbb, 0x35, 0x80, 0xb5,
	0x31, 0x60, 0xd8, 0xbc, 0x75, 0x28, 0x78, 0x04, 0x77, 0x1d, 0xea, 0xe9, 0x86, 0xe4, 0xed, 0x05,
	0xb5, 0x3d, 0xf0, 0xd0, 0x57, 0x80, 0xb0, 0x10, 0xd4, 0x0f, 0x89, 0xa7, 0xa6, 0x83, 0x6e, 0xb9,
	0x52, 0x5f, 0xee, 0xb5, 0x4d, 0x5b, 0x49, 0x6d, 0x52, 0x95, 0x08, 0xeb, 0xaf, 0x79, 0x58, 0x6e,
	0x09, 0x5f, 0x01, 0xe4, 0x6b, 0xda, 0x27, 0x21, 0x11, 0xe2, 0x8d, 0x74, 0x70, 0x21, 0xd4, 0xf9,
	0xb1, 0x50, 0x37, 0xe0, 0x2a, 0x89, 0x98, 0xdb, 0x51, 0x27, 0xb1, 0x24, 0x0a, 0x7a, 0x7f, 0xe0,
	0xa1, 0x87, 0x50, 0xea, 0x09, 0xc2, 0x1d, 0x4e, 0x5c, 0x42, 0x23, 0xa9, 0x25, 0x51, 0x6c, 0xdc,
	0x9c, 0x3c, 0x23, 0x6c, 0x22, 0x39, 0x25, 0x7d, 0x55, 0x1d, 0xcd, 0x7e, 0x30, 0x67, 0x17, 0x95,
	0x75, 0xb2, 0x45, 0xf7, 0xa1, 0x24, 0x06, 0x42, 0x92, 0x40, 0x15, 0x84, 0x3d, 0xd6, 0xca, 0x29,
	0x36, 0xaa, 0x93, 0x9d, 0x3d, 0x7c, 0xaa, 0x52, 0x66, 0x8f, 0x95, 0x93, 0xd8, 0x4a, 0x6f, 0xf7,
	0x3f, 0xce, 0x76, 0xef, 0xfd, 0x29, 0xdd, 0x1b, 0x2b, 0x58, 0xb3, 0x04, 0xa0, 0x2f, 0x75, 0xd4,
	0x1c, 0xb5, 0x02, 0x30, 0xb3, 0x8c, 0xcb, 0x5f, 0x47, 0xf5, 0xda, 0x48, 0x4a, 0xb8, 0xae, 0x5e,
	0xd9, 0xd6, 0x6b, 0x35, 0x3a, 0x38, 0x39, 0xc2, 0xdc, 0x4b, 0x75, 0x99, 0x8b, 0xe7, 0x4b, 0x0c,
	0xc6, 0x8a, 0xb3, 0x7e, 0x89, 0xe7, 0x59, 0x9b, 0xfa, 0x21, 0xee, 0xb6, 0xb1, 0x4c, 0x5e, 0xa8,
	0xb7, 0xda, 0xc5, 0xd9, 0xe7, 0x53, 0x36, 0x0c, 0xeb, 0x99, 0xa1, 0x07, 0x54, 0x16, 0x9f, 0xa1,
	0x22, 0x26, 0x14, 0x02, 0x22, 0x84, 0x1a, 0x99, 0xf1, 0x78, 0x49, 0xb7, 0xe8, 0x33, 0x28, 0x87,
	0xe4, 0xe8, 0x82, 0xf2, 0x73, 0x97, 0x28, 0xbf, 0x14, 0x92, 0xa3, 0xa1, 0xe8, 0x1b, 0xbf, 0xe6,
	0x21, 0xd7, 0x12, 0x3e, 0xf2, 0xa0, 0x34, 0xf6, 0x95, 0xfb, 0x60, 0xb2, 0x58, 0x32, 0x1f, 0x92,
	0xca, 0xed, 0x99, 0x68, 0xc3, 0x04, 0x23, 0x58, 0x7e, 0xe5, 0x5b, 0xf3, 0xe1, 0x54, 0x17, 0x59,
	0x6a, 0x65, 0x6f, 0x66, 0xea, 0xf0, 0xc6, 0xef, 0x01, 0x2e, 0x4c, 0xf5, 0xed, 0xa9, 0x0e, 0x46,
	0xa4, 0xca, 0x47, 0x33, 0x90, 0x86, 0xfe, 0x7d, 0x28, 0x8f, 0x0f, 0x8c, 0x9b, 0x53, 0xad, 0xc7,
	0x78, 0x95, 0xda, 0x6c, 0xbc, 0x8b, 0xa5, 0x7b, 0x45, 0xd6, 0xd3, 0x4b, 0x97, 0xa5, 0xbe, 0xa6,
	0x74, 0xd3, 0xd4, 0x58, 0xb9, 0xf2, 0x83, 0xfa, 0xfd, 0x68, 0xde, 0x79, 0x7e, 0x5a, 0x35, 0x5e,
	0x9c, 0x56, 0x8d, 0xff, 0x4e, 0xab, 0xc6, 0xb3, 0xb3, 0xea, 0xdc, 0x8b, 0xb3, 0xea, 0xdc, 0x3f,
	0x67, 0xd5, 0xb9, 0xef, 0x36, 0x26, 0xe9, 0x5e, 0xff, 0x3e, 0x1d, 0x2e, 0xe8, 0xff, 0xa7, 0x3b,
	0xff, 0x07, 0x00, 0x00, 0xff, 0xff, 0x0d, 0x26, 0xc6, 0xbe, 0x18, 0x0a, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// MsgClient is the client API for Msg service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type MsgClient interface {
	// UpdateParams defines a (governance) operation for updating the module
	// parameters. The authority defaults to the x/gov module account.
	UpdateParams(ctx context.Context, in *MsgUpdateParams, opts ...grpc.CallOption) (*MsgUpdateParamsResponse, error)
	// MsgRegisterProvider allows a Storage Provider to register themselves with the network.
	RegisterProvider(ctx context.Context, in *MsgRegisterProvider, opts ...grpc.CallOption) (*MsgRegisterProviderResponse, error)
	// MsgCreateDeal allows a user to create a new storage deal.
	CreateDeal(ctx context.Context, in *MsgCreateDeal, opts ...grpc.CallOption) (*MsgCreateDealResponse, error)
	// MsgProveLiveness allows a Storage Provider to submit a proof of data liveness.
	ProveLiveness(ctx context.Context, in *MsgProveLiveness, opts ...grpc.CallOption) (*MsgProveLivenessResponse, error)
	// MsgSignalSaturation allows a Storage Provider to signal high load for a deal.
	SignalSaturation(ctx context.Context, in *MsgSignalSaturation, opts ...grpc.CallOption) (*MsgSignalSaturationResponse, error)
}

type msgClient struct {
	cc grpc1.ClientConn
}

func NewMsgClient(cc grpc1.ClientConn) MsgClient {
	return &msgClient{cc}
}

func (c *msgClient) UpdateParams(ctx context.Context, in *MsgUpdateParams, opts ...grpc.CallOption) (*MsgUpdateParamsResponse, error) {
	out := new(MsgUpdateParamsResponse)
	err := c.cc.Invoke(ctx, "/nilchain.nilchain.v1.Msg/UpdateParams", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *msgClient) RegisterProvider(ctx context.Context, in *MsgRegisterProvider, opts ...grpc.CallOption) (*MsgRegisterProviderResponse, error) {
	out := new(MsgRegisterProviderResponse)
	err := c.cc.Invoke(ctx, "/nilchain.nilchain.v1.Msg/RegisterProvider", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *msgClient) CreateDeal(ctx context.Context, in *MsgCreateDeal, opts ...grpc.CallOption) (*MsgCreateDealResponse, error) {
	out := new(MsgCreateDealResponse)
	err := c.cc.Invoke(ctx, "/nilchain.nilchain.v1.Msg/CreateDeal", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *msgClient) ProveLiveness(ctx context.Context, in *MsgProveLiveness, opts ...grpc.CallOption) (*MsgProveLivenessResponse, error) {
	out := new(MsgProveLivenessResponse)
	err := c.cc.Invoke(ctx, "/nilchain.nilchain.v1.Msg/ProveLiveness", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *msgClient) SignalSaturation(ctx context.Context, in *MsgSignalSaturation, opts ...grpc.CallOption) (*MsgSignalSaturationResponse, error) {
	out := new(MsgSignalSaturationResponse)
	err := c.cc.Invoke(ctx, "/nilchain.nilchain.v1.Msg/SignalSaturation", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// MsgServer is the server API for Msg service.
type MsgServer interface {
	// UpdateParams defines a (governance) operation for updating the module
	// parameters. The authority defaults to the x/gov module account.
	UpdateParams(context.Context, *MsgUpdateParams) (*MsgUpdateParamsResponse, error)
	// MsgRegisterProvider allows a Storage Provider to register themselves with the network.
	RegisterProvider(context.Context, *MsgRegisterProvider) (*MsgRegisterProviderResponse, error)
	// MsgCreateDeal allows a user to create a new storage deal.
	CreateDeal(context.Context, *MsgCreateDeal) (*MsgCreateDealResponse, error)
	// MsgProveLiveness allows a Storage Provider to submit a proof of data liveness.
	ProveLiveness(context.Context, *MsgProveLiveness) (*MsgProveLivenessResponse, error)
	// MsgSignalSaturation allows a Storage Provider to signal high load for a deal.
	SignalSaturation(context.Context, *MsgSignalSaturation) (*MsgSignalSaturationResponse, error)
}

// UnimplementedMsgServer can be embedded to have forward compatible implementations.
type UnimplementedMsgServer struct {
}

func (*UnimplementedMsgServer) UpdateParams(ctx context.Context, req *MsgUpdateParams) (*MsgUpdateParamsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateParams not implemented")
}
func (*UnimplementedMsgServer) RegisterProvider(ctx context.Context, req *MsgRegisterProvider) (*MsgRegisterProviderResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RegisterProvider not implemented")
}
func (*UnimplementedMsgServer) CreateDeal(ctx context.Context, req *MsgCreateDeal) (*MsgCreateDealResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateDeal not implemented")
}
func (*UnimplementedMsgServer) ProveLiveness(ctx context.Context, req *MsgProveLiveness) (*MsgProveLivenessResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ProveLiveness not implemented")
}
func (*UnimplementedMsgServer) SignalSaturation(ctx context.Context, req *MsgSignalSaturation) (*MsgSignalSaturationResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SignalSaturation not implemented")
}

func RegisterMsgServer(s grpc1.Server, srv MsgServer) {
	s.RegisterService(&_Msg_serviceDesc, srv)
}

func _Msg_UpdateParams_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MsgUpdateParams)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MsgServer).UpdateParams(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/nilchain.nilchain.v1.Msg/UpdateParams",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MsgServer).UpdateParams(ctx, req.(*MsgUpdateParams))
	}
	return interceptor(ctx, in, info, handler)
}

func _Msg_RegisterProvider_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MsgRegisterProvider)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MsgServer).RegisterProvider(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/nilchain.nilchain.v1.Msg/RegisterProvider",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MsgServer).RegisterProvider(ctx, req.(*MsgRegisterProvider))
	}
	return interceptor(ctx, in, info, handler)
}

func _Msg_CreateDeal_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MsgCreateDeal)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MsgServer).CreateDeal(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/nilchain.nilchain.v1.Msg/CreateDeal",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MsgServer).CreateDeal(ctx, req.(*MsgCreateDeal))
	}
	return interceptor(ctx, in, info, handler)
}

func _Msg_ProveLiveness_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MsgProveLiveness)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MsgServer).ProveLiveness(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/nilchain.nilchain.v1.Msg/ProveLiveness",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MsgServer).ProveLiveness(ctx, req.(*MsgProveLiveness))
	}
	return interceptor(ctx, in, info, handler)
}

func _Msg_SignalSaturation_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MsgSignalSaturation)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MsgServer).SignalSaturation(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/nilchain.nilchain.v1.Msg/SignalSaturation",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MsgServer).SignalSaturation(ctx, req.(*MsgSignalSaturation))
	}
	return interceptor(ctx, in, info, handler)
}

var Msg_serviceDesc = _Msg_serviceDesc
var _Msg_serviceDesc = grpc.ServiceDesc{
	ServiceName: "nilchain.nilchain.v1.Msg",
	HandlerType: (*MsgServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "UpdateParams",
			Handler:    _Msg_UpdateParams_Handler,
		},
		{
			MethodName: "RegisterProvider",
			Handler:    _Msg_RegisterProvider_Handler,
		},
		{
			MethodName: "CreateDeal",
			Handler:    _Msg_CreateDeal_Handler,
		},
		{
			MethodName: "ProveLiveness",
			Handler:    _Msg_ProveLiveness_Handler,
		},
		{
			MethodName: "SignalSaturation",
			Handler:    _Msg_SignalSaturation_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "nilchain/nilchain/v1/tx.proto",
}

func (m *MsgUpdateParams) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *MsgUpdateParams) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *MsgUpdateParams) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	{
		size, err := m.Params.MarshalToSizedBuffer(dAtA[:i])
		if err != nil {
			return 0, err
		}
		i -= size
		i = encodeVarintTx(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0x12
	if len(m.Authority) > 0 {
		i -= len(m.Authority)
		copy(dAtA[i:], m.Authority)
		i = encodeVarintTx(dAtA, i, uint64(len(m.Authority)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *MsgUpdateParamsResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *MsgUpdateParamsResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *MsgUpdateParamsResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	return len(dAtA) - i, nil
}

func (m *MsgRegisterProvider) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *MsgRegisterProvider) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *MsgRegisterProvider) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.TotalStorage != 0 {
		i = encodeVarintTx(dAtA, i, uint64(m.TotalStorage))
		i--
		dAtA[i] = 0x18
	}
	if len(m.Capabilities) > 0 {
		i -= len(m.Capabilities)
		copy(dAtA[i:], m.Capabilities)
		i = encodeVarintTx(dAtA, i, uint64(len(m.Capabilities)))
		i--
		dAtA[i] = 0x12
	}
	if len(m.Creator) > 0 {
		i -= len(m.Creator)
		copy(dAtA[i:], m.Creator)
		i = encodeVarintTx(dAtA, i, uint64(len(m.Creator)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *MsgRegisterProviderResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *MsgRegisterProviderResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *MsgRegisterProviderResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.Success {
		i--
		if m.Success {
			dAtA[i] = 1
		} else {
			dAtA[i] = 0
		}
		i--
		dAtA[i] = 0x8
	}
	return len(dAtA) - i, nil
}

func (m *MsgCreateDeal) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *MsgCreateDeal) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *MsgCreateDeal) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	{
		size := m.InitialEscrowAmount.Size()
		i -= size
		if _, err := m.InitialEscrowAmount.MarshalTo(dAtA[i:]); err != nil {
			return 0, err
		}
		i = encodeVarintTx(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0x3a
	{
		size := m.MaxMonthlySpend.Size()
		i -= size
		if _, err := m.MaxMonthlySpend.MarshalTo(dAtA[i:]); err != nil {
			return 0, err
		}
		i = encodeVarintTx(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0x32
	if len(m.ServiceHint) > 0 {
		i -= len(m.ServiceHint)
		copy(dAtA[i:], m.ServiceHint)
		i = encodeVarintTx(dAtA, i, uint64(len(m.ServiceHint)))
		i--
		dAtA[i] = 0x2a
	}
	if m.DurationBlocks != 0 {
		i = encodeVarintTx(dAtA, i, uint64(m.DurationBlocks))
		i--
		dAtA[i] = 0x20
	}
	if m.Size_ != 0 {
		i = encodeVarintTx(dAtA, i, uint64(m.Size_))
		i--
		dAtA[i] = 0x18
	}
	if len(m.Cid) > 0 {
		i -= len(m.Cid)
		copy(dAtA[i:], m.Cid)
		i = encodeVarintTx(dAtA, i, uint64(len(m.Cid)))
		i--
		dAtA[i] = 0x12
	}
	if len(m.Creator) > 0 {
		i -= len(m.Creator)
		copy(dAtA[i:], m.Creator)
		i = encodeVarintTx(dAtA, i, uint64(len(m.Creator)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *MsgCreateDealResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *MsgCreateDealResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *MsgCreateDealResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.AssignedProviders) > 0 {
		for iNdEx := len(m.AssignedProviders) - 1; iNdEx >= 0; iNdEx-- {
			i -= len(m.AssignedProviders[iNdEx])
			copy(dAtA[i:], m.AssignedProviders[iNdEx])
			i = encodeVarintTx(dAtA, i, uint64(len(m.AssignedProviders[iNdEx])))
			i--
			dAtA[i] = 0x12
		}
	}
	if m.DealId != 0 {
		i = encodeVarintTx(dAtA, i, uint64(m.DealId))
		i--
		dAtA[i] = 0x8
	}
	return len(dAtA) - i, nil
}

func (m *MsgProveLiveness) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *MsgProveLiveness) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *MsgProveLiveness) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.ProofType != nil {
		{
			size := m.ProofType.Size()
			i -= size
			if _, err := m.ProofType.MarshalTo(dAtA[i:]); err != nil {
				return 0, err
			}
		}
	}
	if m.EpochId != 0 {
		i = encodeVarintTx(dAtA, i, uint64(m.EpochId))
		i--
		dAtA[i] = 0x18
	}
	if m.DealId != 0 {
		i = encodeVarintTx(dAtA, i, uint64(m.DealId))
		i--
		dAtA[i] = 0x10
	}
	if len(m.Creator) > 0 {
		i -= len(m.Creator)
		copy(dAtA[i:], m.Creator)
		i = encodeVarintTx(dAtA, i, uint64(len(m.Creator)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *MsgProveLiveness_UserReceipt) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *MsgProveLiveness_UserReceipt) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	if m.UserReceipt != nil {
		{
			size, err := m.UserReceipt.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintTx(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0x22
	}
	return len(dAtA) - i, nil
}
func (m *MsgProveLiveness_SystemProof) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *MsgProveLiveness_SystemProof) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	if m.SystemProof != nil {
		{
			size, err := m.SystemProof.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintTx(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0x2a
	}
	return len(dAtA) - i, nil
}
func (m *MsgProveLivenessResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *MsgProveLivenessResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *MsgProveLivenessResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.RewardAmount) > 0 {
		i -= len(m.RewardAmount)
		copy(dAtA[i:], m.RewardAmount)
		i = encodeVarintTx(dAtA, i, uint64(len(m.RewardAmount)))
		i--
		dAtA[i] = 0x1a
	}
	if m.Tier != 0 {
		i = encodeVarintTx(dAtA, i, uint64(m.Tier))
		i--
		dAtA[i] = 0x10
	}
	if m.Success {
		i--
		if m.Success {
			dAtA[i] = 1
		} else {
			dAtA[i] = 0
		}
		i--
		dAtA[i] = 0x8
	}
	return len(dAtA) - i, nil
}

func (m *MsgSignalSaturation) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *MsgSignalSaturation) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *MsgSignalSaturation) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.DealId != 0 {
		i = encodeVarintTx(dAtA, i, uint64(m.DealId))
		i--
		dAtA[i] = 0x10
	}
	if len(m.Creator) > 0 {
		i -= len(m.Creator)
		copy(dAtA[i:], m.Creator)
		i = encodeVarintTx(dAtA, i, uint64(len(m.Creator)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *MsgSignalSaturationResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *MsgSignalSaturationResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *MsgSignalSaturationResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.NewProviders) > 0 {
		for iNdEx := len(m.NewProviders) - 1; iNdEx >= 0; iNdEx-- {
			i -= len(m.NewProviders[iNdEx])
			copy(dAtA[i:], m.NewProviders[iNdEx])
			i = encodeVarintTx(dAtA, i, uint64(len(m.NewProviders[iNdEx])))
			i--
			dAtA[i] = 0x1a
		}
	}
	if len(m.Message) > 0 {
		i -= len(m.Message)
		copy(dAtA[i:], m.Message)
		i = encodeVarintTx(dAtA, i, uint64(len(m.Message)))
		i--
		dAtA[i] = 0x12
	}
	if m.Success {
		i--
		if m.Success {
			dAtA[i] = 1
		} else {
			dAtA[i] = 0
		}
		i--
		dAtA[i] = 0x8
	}
	return len(dAtA) - i, nil
}

func encodeVarintTx(dAtA []byte, offset int, v uint64) int {
	offset -= sovTx(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *MsgUpdateParams) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Authority)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	l = m.Params.Size()
	n += 1 + l + sovTx(uint64(l))
	return n
}

func (m *MsgUpdateParamsResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	return n
}

func (m *MsgRegisterProvider) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Creator)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	l = len(m.Capabilities)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	if m.TotalStorage != 0 {
		n += 1 + sovTx(uint64(m.TotalStorage))
	}
	return n
}

func (m *MsgRegisterProviderResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.Success {
		n += 2
	}
	return n
}

func (m *MsgCreateDeal) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Creator)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	l = len(m.Cid)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	if m.Size_ != 0 {
		n += 1 + sovTx(uint64(m.Size_))
	}
	if m.DurationBlocks != 0 {
		n += 1 + sovTx(uint64(m.DurationBlocks))
	}
	l = len(m.ServiceHint)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	l = m.MaxMonthlySpend.Size()
	n += 1 + l + sovTx(uint64(l))
	l = m.InitialEscrowAmount.Size()
	n += 1 + l + sovTx(uint64(l))
	return n
}

func (m *MsgCreateDealResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.DealId != 0 {
		n += 1 + sovTx(uint64(m.DealId))
	}
	if len(m.AssignedProviders) > 0 {
		for _, s := range m.AssignedProviders {
			l = len(s)
			n += 1 + l + sovTx(uint64(l))
		}
	}
	return n
}

func (m *MsgProveLiveness) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Creator)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	if m.DealId != 0 {
		n += 1 + sovTx(uint64(m.DealId))
	}
	if m.EpochId != 0 {
		n += 1 + sovTx(uint64(m.EpochId))
	}
	if m.ProofType != nil {
		n += m.ProofType.Size()
	}
	return n
}

func (m *MsgProveLiveness_UserReceipt) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.UserReceipt != nil {
		l = m.UserReceipt.Size()
		n += 1 + l + sovTx(uint64(l))
	}
	return n
}
func (m *MsgProveLiveness_SystemProof) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.SystemProof != nil {
		l = m.SystemProof.Size()
		n += 1 + l + sovTx(uint64(l))
	}
	return n
}
func (m *MsgProveLivenessResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.Success {
		n += 2
	}
	if m.Tier != 0 {
		n += 1 + sovTx(uint64(m.Tier))
	}
	l = len(m.RewardAmount)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	return n
}

func (m *MsgSignalSaturation) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Creator)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	if m.DealId != 0 {
		n += 1 + sovTx(uint64(m.DealId))
	}
	return n
}

func (m *MsgSignalSaturationResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.Success {
		n += 2
	}
	l = len(m.Message)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	if len(m.NewProviders) > 0 {
		for _, s := range m.NewProviders {
			l = len(s)
			n += 1 + l + sovTx(uint64(l))
		}
	}
	return n
}

func sovTx(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozTx(x uint64) (n int) {
	return sovTx(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *MsgUpdateParams) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTx
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: MsgUpdateParams: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: MsgUpdateParams: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Authority", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Authority = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Params", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.Params.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipTx(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTx
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *MsgUpdateParamsResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTx
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: MsgUpdateParamsResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: MsgUpdateParamsResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		default:
			iNdEx = preIndex
			skippy, err := skipTx(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTx
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *MsgRegisterProvider) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTx
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: MsgRegisterProvider: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: MsgRegisterProvider: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Creator", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Creator = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Capabilities", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Capabilities = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 3:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field TotalStorage", wireType)
			}
			m.TotalStorage = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.TotalStorage |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		default:
			iNdEx = preIndex
			skippy, err := skipTx(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTx
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *MsgRegisterProviderResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTx
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: MsgRegisterProviderResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: MsgRegisterProviderResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Success", wireType)
			}
			var v int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				v |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			m.Success = bool(v != 0)
		default:
			iNdEx = preIndex
			skippy, err := skipTx(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTx
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *MsgCreateDeal) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTx
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: MsgCreateDeal: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: MsgCreateDeal: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Creator", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Creator = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Cid", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Cid = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 3:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Size_", wireType)
			}
			m.Size_ = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Size_ |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 4:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field DurationBlocks", wireType)
			}
			m.DurationBlocks = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.DurationBlocks |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 5:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field ServiceHint", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.ServiceHint = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 6:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field MaxMonthlySpend", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.MaxMonthlySpend.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 7:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field InitialEscrowAmount", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.InitialEscrowAmount.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipTx(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTx
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *MsgCreateDealResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTx
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: MsgCreateDealResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: MsgCreateDealResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field DealId", wireType)
			}
			m.DealId = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.DealId |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field AssignedProviders", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.AssignedProviders = append(m.AssignedProviders, string(dAtA[iNdEx:postIndex]))
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipTx(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTx
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *MsgProveLiveness) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTx
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: MsgProveLiveness: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: MsgProveLiveness: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Creator", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Creator = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field DealId", wireType)
			}
			m.DealId = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.DealId |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 3:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field EpochId", wireType)
			}
			m.EpochId = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.EpochId |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 4:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field UserReceipt", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			v := &RetrievalReceipt{}
			if err := v.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			m.ProofType = &MsgProveLiveness_UserReceipt{v}
			iNdEx = postIndex
		case 5:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field SystemProof", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			v := &KzgProof{}
			if err := v.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			m.ProofType = &MsgProveLiveness_SystemProof{v}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipTx(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTx
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *MsgProveLivenessResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTx
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: MsgProveLivenessResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: MsgProveLivenessResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Success", wireType)
			}
			var v int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				v |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			m.Success = bool(v != 0)
		case 2:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Tier", wireType)
			}
			m.Tier = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Tier |= uint32(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field RewardAmount", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.RewardAmount = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipTx(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTx
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *MsgSignalSaturation) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTx
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: MsgSignalSaturation: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: MsgSignalSaturation: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Creator", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Creator = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field DealId", wireType)
			}
			m.DealId = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.DealId |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		default:
			iNdEx = preIndex
			skippy, err := skipTx(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTx
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *MsgSignalSaturationResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTx
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: MsgSignalSaturationResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: MsgSignalSaturationResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Success", wireType)
			}
			var v int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				v |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			m.Success = bool(v != 0)
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Message", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Message = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field NewProviders", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.NewProviders = append(m.NewProviders, string(dAtA[iNdEx:postIndex]))
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipTx(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTx
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipTx(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowTx
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowTx
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowTx
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthTx
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupTx
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthTx
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthTx        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowTx          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupTx = fmt.Errorf("proto: unexpected end of group")
)
