// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: nilchain/nilchain/v1/types.proto

package types

import (
	cosmossdk_io_math "cosmossdk.io/math"
	fmt "fmt"
	_ "github.com/cosmos/cosmos-proto"
	_ "github.com/cosmos/gogoproto/gogoproto"
	proto "github.com/cosmos/gogoproto/proto"
	io "io"
	math "math"
	math_bits "math/bits"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

// DealSize represents the authorized capacity tiers for storage deals.
type DealSize int32

const (
	DealSize_DEAL_SIZE_UNSPECIFIED DealSize = 0
	DealSize_DEAL_SIZE_4GIB        DealSize = 1
	DealSize_DEAL_SIZE_32GIB       DealSize = 2
	DealSize_DEAL_SIZE_512GIB      DealSize = 3
)

var DealSize_name = map[int32]string{
	0: "DEAL_SIZE_UNSPECIFIED",
	1: "DEAL_SIZE_4GIB",
	2: "DEAL_SIZE_32GIB",
	3: "DEAL_SIZE_512GIB",
}

var DealSize_value = map[string]int32{
	"DEAL_SIZE_UNSPECIFIED": 0,
	"DEAL_SIZE_4GIB":        1,
	"DEAL_SIZE_32GIB":       2,
	"DEAL_SIZE_512GIB":      3,
}

func (x DealSize) String() string {
	return proto.EnumName(DealSize_name, int32(x))
}

func (DealSize) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_8cb128e800f8f092, []int{0}
}

// Deal represents a storage deal between a user and the network.
type Deal struct {
	Id                 uint64                `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Cid                string                `protobuf:"bytes,2,opt,name=cid,proto3" json:"cid,omitempty"`
	Size_              uint64                `protobuf:"varint,3,opt,name=size,proto3" json:"size,omitempty"`
	Owner              string                `protobuf:"bytes,4,opt,name=owner,proto3" json:"owner,omitempty"`
	EscrowBalance      cosmossdk_io_math.Int `protobuf:"bytes,5,opt,name=escrow_balance,json=escrowBalance,proto3,customtype=cosmossdk.io/math.Int" json:"escrow_balance"`
	StartBlock         uint64                `protobuf:"varint,6,opt,name=start_block,json=startBlock,proto3" json:"start_block,omitempty"`
	EndBlock           uint64                `protobuf:"varint,7,opt,name=end_block,json=endBlock,proto3" json:"end_block,omitempty"`
	Providers          []string              `protobuf:"bytes,8,rep,name=providers,proto3" json:"providers,omitempty"`
	RedundancyMode     uint32                `protobuf:"varint,9,opt,name=redundancy_mode,json=redundancyMode,proto3" json:"redundancy_mode,omitempty"`
	CurrentReplication uint64                `protobuf:"varint,10,opt,name=current_replication,json=currentReplication,proto3" json:"current_replication,omitempty"`
	ServiceHint        string                `protobuf:"bytes,11,opt,name=service_hint,json=serviceHint,proto3" json:"service_hint,omitempty"`
	MaxMonthlySpend    cosmossdk_io_math.Int `protobuf:"bytes,12,opt,name=max_monthly_spend,json=maxMonthlySpend,proto3,customtype=cosmossdk.io/math.Int" json:"max_monthly_spend"`
	DealSize           DealSize              `protobuf:"varint,13,opt,name=deal_size,json=dealSize,proto3,enum=nilchain.nilchain.v1.DealSize" json:"deal_size,omitempty"`
}

func (m *Deal) Reset()         { *m = Deal{} }
func (m *Deal) String() string { return proto.CompactTextString(m) }
func (*Deal) ProtoMessage()    {}
func (*Deal) Descriptor() ([]byte, []int) {
	return fileDescriptor_8cb128e800f8f092, []int{0}
}
func (m *Deal) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *Deal) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_Deal.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *Deal) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Deal.Merge(m, src)
}
func (m *Deal) XXX_Size() int {
	return m.Size()
}
func (m *Deal) XXX_DiscardUnknown() {
	xxx_messageInfo_Deal.DiscardUnknown(m)
}

var xxx_messageInfo_Deal proto.InternalMessageInfo

func (m *Deal) GetId() uint64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *Deal) GetCid() string {
	if m != nil {
		return m.Cid
	}
	return ""
}

func (m *Deal) GetSize_() uint64 {
	if m != nil {
		return m.Size_
	}
	return 0
}

func (m *Deal) GetOwner() string {
	if m != nil {
		return m.Owner
	}
	return ""
}

func (m *Deal) GetStartBlock() uint64 {
	if m != nil {
		return m.StartBlock
	}
	return 0
}

func (m *Deal) GetEndBlock() uint64 {
	if m != nil {
		return m.EndBlock
	}
	return 0
}

func (m *Deal) GetProviders() []string {
	if m != nil {
		return m.Providers
	}
	return nil
}

func (m *Deal) GetRedundancyMode() uint32 {
	if m != nil {
		return m.RedundancyMode
	}
	return 0
}

func (m *Deal) GetCurrentReplication() uint64 {
	if m != nil {
		return m.CurrentReplication
	}
	return 0
}

func (m *Deal) GetServiceHint() string {
	if m != nil {
		return m.ServiceHint
	}
	return ""
}

func (m *Deal) GetDealSize() DealSize {
	if m != nil {
		return m.DealSize
	}
	return DealSize_DEAL_SIZE_UNSPECIFIED
}

// DealHeatState tracks aggregate traffic and performance metrics for a deal.
// Used for "Heat" observability and potential future economic tilting.
type DealHeatState struct {
	BytesServedTotal      uint64 `protobuf:"varint,1,opt,name=bytes_served_total,json=bytesServedTotal,proto3" json:"bytes_served_total,omitempty"`
	FailedChallengesTotal uint64 `protobuf:"varint,2,opt,name=failed_challenges_total,json=failedChallengesTotal,proto3" json:"failed_challenges_total,omitempty"`
	LastUpdateHeight      int64  `protobuf:"varint,3,opt,name=last_update_height,json=lastUpdateHeight,proto3" json:"last_update_height,omitempty"`
}

func (m *DealHeatState) Reset()         { *m = DealHeatState{} }
func (m *DealHeatState) String() string { return proto.CompactTextString(m) }
func (*DealHeatState) ProtoMessage()    {}
func (*DealHeatState) Descriptor() ([]byte, []int) {
	return fileDescriptor_8cb128e800f8f092, []int{1}
}
func (m *DealHeatState) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *DealHeatState) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_DealHeatState.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *DealHeatState) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DealHeatState.Merge(m, src)
}
func (m *DealHeatState) XXX_Size() int {
	return m.Size()
}
func (m *DealHeatState) XXX_DiscardUnknown() {
	xxx_messageInfo_DealHeatState.DiscardUnknown(m)
}

var xxx_messageInfo_DealHeatState proto.InternalMessageInfo

func (m *DealHeatState) GetBytesServedTotal() uint64 {
	if m != nil {
		return m.BytesServedTotal
	}
	return 0
}

func (m *DealHeatState) GetFailedChallengesTotal() uint64 {
	if m != nil {
		return m.FailedChallengesTotal
	}
	return 0
}

func (m *DealHeatState) GetLastUpdateHeight() int64 {
	if m != nil {
		return m.LastUpdateHeight
	}
	return 0
}

// Provider represents a Storage Provider in the network.
type Provider struct {
	Address         string `protobuf:"bytes,1,opt,name=address,proto3" json:"address,omitempty"`
	TotalStorage    uint64 `protobuf:"varint,2,opt,name=total_storage,json=totalStorage,proto3" json:"total_storage,omitempty"`
	UsedStorage     uint64 `protobuf:"varint,3,opt,name=used_storage,json=usedStorage,proto3" json:"used_storage,omitempty"`
	Capabilities    string `protobuf:"bytes,4,opt,name=capabilities,proto3" json:"capabilities,omitempty"`
	Status          string `protobuf:"bytes,5,opt,name=status,proto3" json:"status,omitempty"`
	ReputationScore int64  `protobuf:"varint,6,opt,name=reputation_score,json=reputationScore,proto3" json:"reputation_score,omitempty"`
}

func (m *Provider) Reset()         { *m = Provider{} }
func (m *Provider) String() string { return proto.CompactTextString(m) }
func (*Provider) ProtoMessage()    {}
func (*Provider) Descriptor() ([]byte, []int) {
	return fileDescriptor_8cb128e800f8f092, []int{2}
}
func (m *Provider) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *Provider) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_Provider.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *Provider) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Provider.Merge(m, src)
}
func (m *Provider) XXX_Size() int {
	return m.Size()
}
func (m *Provider) XXX_DiscardUnknown() {
	xxx_messageInfo_Provider.DiscardUnknown(m)
}

var xxx_messageInfo_Provider proto.InternalMessageInfo

func (m *Provider) GetAddress() string {
	if m != nil {
		return m.Address
	}
	return ""
}

func (m *Provider) GetTotalStorage() uint64 {
	if m != nil {
		return m.TotalStorage
	}
	return 0
}

func (m *Provider) GetUsedStorage() uint64 {
	if m != nil {
		return m.UsedStorage
	}
	return 0
}

func (m *Provider) GetCapabilities() string {
	if m != nil {
		return m.Capabilities
	}
	return ""
}

func (m *Provider) GetStatus() string {
	if m != nil {
		return m.Status
	}
	return ""
}

func (m *Provider) GetReputationScore() int64 {
	if m != nil {
		return m.ReputationScore
	}
	return 0
}

// VirtualStripe tracks overlay replicas for a deal, used for elasticity.
type VirtualStripe struct {
	DealId           uint64   `protobuf:"varint,1,opt,name=deal_id,json=dealId,proto3" json:"deal_id,omitempty"`
	StripeIndex      uint32   `protobuf:"varint,2,opt,name=stripe_index,json=stripeIndex,proto3" json:"stripe_index,omitempty"`
	OverlayProviders []string `protobuf:"bytes,3,rep,name=overlay_providers,json=overlayProviders,proto3" json:"overlay_providers,omitempty"`
}

func (m *VirtualStripe) Reset()         { *m = VirtualStripe{} }
func (m *VirtualStripe) String() string { return proto.CompactTextString(m) }
func (*VirtualStripe) ProtoMessage()    {}
func (*VirtualStripe) Descriptor() ([]byte, []int) {
	return fileDescriptor_8cb128e800f8f092, []int{3}
}
func (m *VirtualStripe) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *VirtualStripe) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_VirtualStripe.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *VirtualStripe) XXX_Merge(src proto.Message) {
	xxx_messageInfo_VirtualStripe.Merge(m, src)
}
func (m *VirtualStripe) XXX_Size() int {
	return m.Size()
}
func (m *VirtualStripe) XXX_DiscardUnknown() {
	xxx_messageInfo_VirtualStripe.DiscardUnknown(m)
}

var xxx_messageInfo_VirtualStripe proto.InternalMessageInfo

func (m *VirtualStripe) GetDealId() uint64 {
	if m != nil {
		return m.DealId
	}
	return 0
}

func (m *VirtualStripe) GetStripeIndex() uint32 {
	if m != nil {
		return m.StripeIndex
	}
	return 0
}

func (m *VirtualStripe) GetOverlayProviders() []string {
	if m != nil {
		return m.OverlayProviders
	}
	return nil
}

// KzgProof represents a KZG proof for a single 128 KiB blob within an 8 MiB MDU,
// along with the Merkle proof connecting it to the MDU's root.
type KzgProof struct {
	MduMerkleRoot                     []byte   `protobuf:"bytes,1,opt,name=mdu_merkle_root,json=mduMerkleRoot,proto3" json:"mdu_merkle_root,omitempty"`
	ChallengedKzgCommitment           []byte   `protobuf:"bytes,2,opt,name=challenged_kzg_commitment,json=challengedKzgCommitment,proto3" json:"challenged_kzg_commitment,omitempty"`
	ChallengedKzgCommitmentMerklePath [][]byte `protobuf:"bytes,3,rep,name=challenged_kzg_commitment_merkle_path,json=challengedKzgCommitmentMerklePath,proto3" json:"challenged_kzg_commitment_merkle_path,omitempty"`
	ChallengedKzgCommitmentIndex      uint32   `protobuf:"varint,4,opt,name=challenged_kzg_commitment_index,json=challengedKzgCommitmentIndex,proto3" json:"challenged_kzg_commitment_index,omitempty"`
	ZValue                            []byte   `protobuf:"bytes,5,opt,name=z_value,json=zValue,proto3" json:"z_value,omitempty"`
	YValue                            []byte   `protobuf:"bytes,6,opt,name=y_value,json=yValue,proto3" json:"y_value,omitempty"`
	KzgOpeningProof                   []byte   `protobuf:"bytes,7,opt,name=kzg_opening_proof,json=kzgOpeningProof,proto3" json:"kzg_opening_proof,omitempty"`
}

func (m *KzgProof) Reset()         { *m = KzgProof{} }
func (m *KzgProof) String() string { return proto.CompactTextString(m) }
func (*KzgProof) ProtoMessage()    {}
func (*KzgProof) Descriptor() ([]byte, []int) {
	return fileDescriptor_8cb128e800f8f092, []int{4}
}
func (m *KzgProof) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *KzgProof) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_KzgProof.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *KzgProof) XXX_Merge(src proto.Message) {
	xxx_messageInfo_KzgProof.Merge(m, src)
}
func (m *KzgProof) XXX_Size() int {
	return m.Size()
}
func (m *KzgProof) XXX_DiscardUnknown() {
	xxx_messageInfo_KzgProof.DiscardUnknown(m)
}

var xxx_messageInfo_KzgProof proto.InternalMessageInfo

func (m *KzgProof) GetMduMerkleRoot() []byte {
	if m != nil {
		return m.MduMerkleRoot
	}
	return nil
}

func (m *KzgProof) GetChallengedKzgCommitment() []byte {
	if m != nil {
		return m.ChallengedKzgCommitment
	}
	return nil
}

func (m *KzgProof) GetChallengedKzgCommitmentMerklePath() [][]byte {
	if m != nil {
		return m.ChallengedKzgCommitmentMerklePath
	}
	return nil
}

func (m *KzgProof) GetChallengedKzgCommitmentIndex() uint32 {
	if m != nil {
		return m.ChallengedKzgCommitmentIndex
	}
	return 0
}

func (m *KzgProof) GetZValue() []byte {
	if m != nil {
		return m.ZValue
	}
	return nil
}

func (m *KzgProof) GetYValue() []byte {
	if m != nil {
		return m.YValue
	}
	return nil
}

func (m *KzgProof) GetKzgOpeningProof() []byte {
	if m != nil {
		return m.KzgOpeningProof
	}
	return nil
}

// RetrievalReceipt represents a user's signed confirmation of data retrieval.
type RetrievalReceipt struct {
	DealId        uint64   `protobuf:"varint,1,opt,name=deal_id,json=dealId,proto3" json:"deal_id,omitempty"`
	EpochId       uint64   `protobuf:"varint,2,opt,name=epoch_id,json=epochId,proto3" json:"epoch_id,omitempty"`
	Provider      string   `protobuf:"bytes,3,opt,name=provider,proto3" json:"provider,omitempty"`
	BytesServed   uint64   `protobuf:"varint,4,opt,name=bytes_served,json=bytesServed,proto3" json:"bytes_served,omitempty"`
	ProofDetails  KzgProof `protobuf:"bytes,5,opt,name=proof_details,json=proofDetails,proto3" json:"proof_details"`
	UserSignature []byte   `protobuf:"bytes,6,opt,name=user_signature,json=userSignature,proto3" json:"user_signature,omitempty"`
	Nonce         uint64   `protobuf:"varint,7,opt,name=nonce,proto3" json:"nonce,omitempty"`
	ExpiresAt     uint64   `protobuf:"varint,8,opt,name=expires_at,json=expiresAt,proto3" json:"expires_at,omitempty"`
}

func (m *RetrievalReceipt) Reset()         { *m = RetrievalReceipt{} }
func (m *RetrievalReceipt) String() string { return proto.CompactTextString(m) }
func (*RetrievalReceipt) ProtoMessage()    {}
func (*RetrievalReceipt) Descriptor() ([]byte, []int) {
	return fileDescriptor_8cb128e800f8f092, []int{5}
}
func (m *RetrievalReceipt) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *RetrievalReceipt) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_RetrievalReceipt.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *RetrievalReceipt) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RetrievalReceipt.Merge(m, src)
}
func (m *RetrievalReceipt) XXX_Size() int {
	return m.Size()
}
func (m *RetrievalReceipt) XXX_DiscardUnknown() {
	xxx_messageInfo_RetrievalReceipt.DiscardUnknown(m)
}

var xxx_messageInfo_RetrievalReceipt proto.InternalMessageInfo

func (m *RetrievalReceipt) GetDealId() uint64 {
	if m != nil {
		return m.DealId
	}
	return 0
}

func (m *RetrievalReceipt) GetEpochId() uint64 {
	if m != nil {
		return m.EpochId
	}
	return 0
}

func (m *RetrievalReceipt) GetProvider() string {
	if m != nil {
		return m.Provider
	}
	return ""
}

func (m *RetrievalReceipt) GetBytesServed() uint64 {
	if m != nil {
		return m.BytesServed
	}
	return 0
}

func (m *RetrievalReceipt) GetProofDetails() KzgProof {
	if m != nil {
		return m.ProofDetails
	}
	return KzgProof{}
}

func (m *RetrievalReceipt) GetUserSignature() []byte {
	if m != nil {
		return m.UserSignature
	}
	return nil
}

func (m *RetrievalReceipt) GetNonce() uint64 {
	if m != nil {
		return m.Nonce
	}
	return 0
}

func (m *RetrievalReceipt) GetExpiresAt() uint64 {
	if m != nil {
		return m.ExpiresAt
	}
	return 0
}

func init() {
	proto.RegisterEnum("nilchain.nilchain.v1.DealSize", DealSize_name, DealSize_value)
	proto.RegisterType((*Deal)(nil), "nilchain.nilchain.v1.Deal")
	proto.RegisterType((*DealHeatState)(nil), "nilchain.nilchain.v1.DealHeatState")
	proto.RegisterType((*Provider)(nil), "nilchain.nilchain.v1.Provider")
	proto.RegisterType((*VirtualStripe)(nil), "nilchain.nilchain.v1.VirtualStripe")
	proto.RegisterType((*KzgProof)(nil), "nilchain.nilchain.v1.KzgProof")
	proto.RegisterType((*RetrievalReceipt)(nil), "nilchain.nilchain.v1.RetrievalReceipt")
}

func init() { proto.RegisterFile("nilchain/nilchain/v1/types.proto", fileDescriptor_8cb128e800f8f092) }

var fileDescriptor_8cb128e800f8f092 = []byte{
	// 1082 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x8c, 0x55, 0x4f, 0x6f, 0x1b, 0x45,
	0x14, 0x8f, 0xff, 0x34, 0x71, 0x9e, 0xed, 0xc4, 0x9d, 0xa6, 0x64, 0x53, 0xa8, 0x93, 0x1a, 0x15,
	0x42, 0x55, 0x1c, 0xf5, 0x0f, 0x3d, 0xc0, 0xa9, 0x69, 0x02, 0xb5, 0x4a, 0x21, 0x5a, 0xd3, 0x1e,
	0x7a, 0x19, 0x4d, 0x76, 0x5e, 0xd7, 0xa3, 0xec, 0xee, 0xac, 0x66, 0x66, 0xdd, 0xd8, 0x9f, 0x02,
	0xf1, 0x15, 0x38, 0x73, 0xe3, 0x33, 0xa0, 0x1e, 0x2b, 0x4e, 0x88, 0x43, 0x85, 0x5a, 0x71, 0xe4,
	0x3b, 0xa0, 0x99, 0x59, 0xdb, 0x45, 0x22, 0x81, 0xdb, 0xbc, 0xdf, 0xef, 0xfd, 0x66, 0xdf, 0xbe,
	0x7f, 0x03, 0x3b, 0x99, 0x48, 0xa2, 0x11, 0x13, 0xd9, 0xde, 0xfc, 0x30, 0xbe, 0xb5, 0x67, 0x26,
	0x39, 0xea, 0x7e, 0xae, 0xa4, 0x91, 0x64, 0x63, 0x46, 0xf4, 0xe7, 0x87, 0xf1, 0xad, 0x2b, 0x1b,
	0xb1, 0x8c, 0xa5, 0x73, 0xd8, 0xb3, 0x27, 0xef, 0x7b, 0x65, 0x2b, 0x92, 0x3a, 0x95, 0x9a, 0x7a,
	0xc2, 0x1b, 0x9e, 0xea, 0xfd, 0x54, 0x87, 0xfa, 0x01, 0xb2, 0x84, 0xac, 0x41, 0x55, 0xf0, 0xa0,
	0xb2, 0x53, 0xd9, 0xad, 0x87, 0x55, 0xc1, 0x49, 0x07, 0x6a, 0x91, 0xe0, 0x41, 0x75, 0xa7, 0xb2,
	0xbb, 0x1a, 0xda, 0x23, 0x21, 0x50, 0xd7, 0x62, 0x8a, 0x41, 0xcd, 0xf9, 0xb8, 0x33, 0xe9, 0xc3,
	0x05, 0xf9, 0x22, 0x43, 0x15, 0xd4, 0xad, 0xdf, 0x7e, 0xf0, 0xeb, 0xcf, 0x9f, 0x6e, 0x94, 0xf7,
	0xdf, 0xe7, 0x5c, 0xa1, 0xd6, 0x43, 0xa3, 0x44, 0x16, 0x87, 0xde, 0x8d, 0x1c, 0xc0, 0x1a, 0xea,
	0x48, 0xc9, 0x17, 0xf4, 0x98, 0x25, 0x2c, 0x8b, 0x30, 0xb8, 0xe0, 0x84, 0x57, 0x5f, 0xbe, 0xde,
	0x5e, 0xfa, 0xfd, 0xf5, 0xf6, 0x65, 0x2f, 0xd6, 0xfc, 0xa4, 0x2f, 0xe4, 0x5e, 0xca, 0xcc, 0xa8,
	0x3f, 0xc8, 0x4c, 0xd8, 0xf6, 0xa2, 0x7d, 0xaf, 0x21, 0xdb, 0xd0, 0xd4, 0x86, 0x29, 0x43, 0x8f,
	0x13, 0x19, 0x9d, 0x04, 0xcb, 0x2e, 0x20, 0x70, 0xd0, 0xbe, 0x45, 0xc8, 0xfb, 0xb0, 0x8a, 0x19,
	0x2f, 0xe9, 0x15, 0x47, 0x37, 0x30, 0xe3, 0x9e, 0xbc, 0x07, 0xab, 0xb9, 0x92, 0x63, 0xc1, 0x51,
	0xe9, 0xa0, 0xb1, 0x53, 0x3b, 0x37, 0xee, 0x85, 0x2b, 0xf9, 0x18, 0xd6, 0x15, 0xf2, 0x22, 0xe3,
	0x2c, 0x8b, 0x26, 0x34, 0x95, 0x1c, 0x83, 0xd5, 0x9d, 0xca, 0x6e, 0x3b, 0x5c, 0x5b, 0xc0, 0x8f,
	0x25, 0x47, 0xb2, 0x07, 0x97, 0xa2, 0x42, 0x29, 0xcc, 0x0c, 0x55, 0x98, 0x27, 0x22, 0x62, 0x46,
	0xc8, 0x2c, 0x00, 0x17, 0x07, 0x29, 0xa9, 0x70, 0xc1, 0x90, 0x6b, 0xd0, 0xd2, 0xa8, 0xc6, 0x22,
	0x42, 0x3a, 0x12, 0x99, 0x09, 0x9a, 0x2e, 0xe9, 0xcd, 0x12, 0x7b, 0x28, 0x32, 0x43, 0x06, 0x70,
	0x31, 0x65, 0xa7, 0x34, 0x95, 0x99, 0x19, 0x25, 0x13, 0xaa, 0x73, 0xcc, 0x78, 0xd0, 0xfa, 0x3f,
	0xb9, 0x5b, 0x4f, 0xd9, 0xe9, 0x63, 0x2f, 0x1b, 0x5a, 0x15, 0xf9, 0x02, 0x56, 0x39, 0xb2, 0x84,
	0xba, 0x62, 0xb6, 0x77, 0x2a, 0xbb, 0x6b, 0xb7, 0xbb, 0xfd, 0x7f, 0xeb, 0xa6, 0xbe, 0x6d, 0x8c,
	0xa1, 0x98, 0x62, 0xd8, 0xe0, 0xe5, 0xa9, 0xf7, 0x63, 0x05, 0xda, 0x16, 0x7e, 0x88, 0xcc, 0x0c,
	0x0d, 0x33, 0x48, 0x6e, 0x02, 0x39, 0x9e, 0x18, 0xd4, 0xd4, 0x86, 0x8b, 0x9c, 0x1a, 0x69, 0x58,
	0x52, 0x36, 0x52, 0xc7, 0x31, 0x43, 0x47, 0x7c, 0x67, 0x71, 0x72, 0x0f, 0x36, 0x9f, 0x33, 0x91,
	0x20, 0xa7, 0xd1, 0x88, 0x25, 0x09, 0x66, 0x31, 0xea, 0x52, 0x52, 0x75, 0x92, 0xcb, 0x9e, 0x7e,
	0x30, 0x67, 0xbd, 0xee, 0x26, 0x90, 0x84, 0x69, 0x43, 0x8b, 0x9c, 0x33, 0x83, 0x74, 0x84, 0x22,
	0x1e, 0x19, 0xd7, 0x8a, 0xb5, 0xb0, 0x63, 0x99, 0x27, 0x8e, 0x78, 0xe8, 0xf0, 0xde, 0x5f, 0x15,
	0x68, 0x1c, 0x95, 0x85, 0x23, 0xb7, 0x61, 0x85, 0xf9, 0x9a, 0xba, 0xa8, 0xce, 0xab, 0xf6, 0xcc,
	0x91, 0x7c, 0x08, 0x6d, 0x17, 0x14, 0xd5, 0x46, 0x2a, 0x16, 0x63, 0x19, 0x5c, 0xcb, 0x81, 0x43,
	0x8f, 0xd9, 0xb2, 0x15, 0x1a, 0xf9, 0xdc, 0xc7, 0x0f, 0x46, 0xd3, 0x62, 0x33, 0x97, 0x1e, 0xb4,
	0x22, 0x96, 0xb3, 0x63, 0x91, 0x08, 0x23, 0x50, 0xfb, 0x31, 0x09, 0xff, 0x81, 0x91, 0xf7, 0x60,
	0x59, 0x1b, 0x66, 0x0a, 0xed, 0x67, 0x21, 0x2c, 0x2d, 0xf2, 0x09, 0x74, 0x14, 0xe6, 0x85, 0x71,
	0x3d, 0x42, 0x75, 0x24, 0x15, 0xba, 0x56, 0xaf, 0x85, 0xeb, 0x0b, 0x7c, 0x68, 0xe1, 0xde, 0x0f,
	0x15, 0x68, 0x3f, 0x15, 0xca, 0x14, 0x36, 0x38, 0x25, 0x72, 0x24, 0x9b, 0xb0, 0xe2, 0x8a, 0x3c,
	0x9f, 0xe9, 0x65, 0x6b, 0x0e, 0xb8, 0xeb, 0x35, 0xe7, 0x42, 0x45, 0xc6, 0xf1, 0xd4, 0xfd, 0x58,
	0x3b, 0x6c, 0x7a, 0x6c, 0x60, 0x21, 0x72, 0x08, 0x17, 0xe5, 0x18, 0x55, 0xc2, 0x26, 0x74, 0x31,
	0x28, 0xb5, 0xff, 0x18, 0x94, 0x4e, 0x29, 0x99, 0xa5, 0x5d, 0xf7, 0xfe, 0xac, 0x42, 0xe3, 0xd1,
	0x34, 0x3e, 0x52, 0x52, 0x3e, 0x27, 0x1f, 0xc1, 0x7a, 0xca, 0x0b, 0x9a, 0xa2, 0x3a, 0x49, 0x90,
	0x2a, 0x29, 0x8d, 0x8b, 0xab, 0x15, 0xb6, 0x53, 0x5e, 0x3c, 0x76, 0x68, 0x28, 0xa5, 0x21, 0x9f,
	0xc3, 0xd6, 0xbc, 0x31, 0x38, 0x3d, 0x99, 0xc6, 0x34, 0x92, 0x69, 0x2a, 0x4c, 0x8a, 0x99, 0x71,
	0xb1, 0xb6, 0xc2, 0xcd, 0x85, 0xc3, 0xa3, 0x69, 0xfc, 0x60, 0x4e, 0x93, 0x23, 0xb8, 0x7e, 0xa6,
	0x76, 0xf6, 0xe5, 0x9c, 0x99, 0x91, 0xfb, 0x97, 0x56, 0x78, 0xed, 0x8c, 0x7b, 0x7c, 0x34, 0x47,
	0xcc, 0x8c, 0xc8, 0x21, 0x6c, 0x9f, 0x7d, 0xa3, 0xcf, 0x5f, 0xdd, 0xe5, 0xef, 0x83, 0x33, 0xee,
	0xf2, 0x09, 0xdd, 0x84, 0x95, 0x29, 0x1d, 0xb3, 0xa4, 0xf0, 0xeb, 0xae, 0x15, 0x2e, 0x4f, 0x9f,
	0x5a, 0xcb, 0x12, 0x93, 0x92, 0x58, 0xf6, 0xc4, 0xc4, 0x13, 0x37, 0xe0, 0xa2, 0xfd, 0x9a, 0xcc,
	0x31, 0x13, 0x59, 0x6c, 0xcb, 0x20, 0x9f, 0xbb, 0x45, 0xd6, 0x0a, 0xd7, 0x4f, 0xa6, 0xf1, 0xb7,
	0x1e, 0x77, 0xa9, 0xed, 0xfd, 0x52, 0x85, 0x4e, 0x88, 0x46, 0x09, 0x1c, 0xb3, 0x24, 0xc4, 0x08,
	0x45, 0x6e, 0xce, 0xae, 0xff, 0x16, 0x34, 0x30, 0x97, 0xd1, 0x88, 0x96, 0xcb, 0xbd, 0x1e, 0xae,
	0x38, 0x7b, 0xc0, 0xc9, 0x5d, 0x68, 0xcc, 0xea, 0xed, 0x7a, 0xf9, 0xbc, 0x72, 0xcf, 0x3d, 0x6d,
	0x43, 0xbd, 0x3b, 0xff, 0x2e, 0x21, 0xf5, 0xb0, 0xf9, 0xce, 0xe4, 0x93, 0x01, 0xb4, 0xdd, 0x1f,
	0x50, 0x8e, 0x86, 0x89, 0xc4, 0x37, 0x7a, 0xf3, 0xac, 0xad, 0x33, 0xeb, 0x99, 0xfd, 0xba, 0x5d,
	0x6c, 0x61, 0xcb, 0x49, 0x0f, 0xbc, 0x92, 0x5c, 0x87, 0xb5, 0x42, 0xa3, 0xa2, 0x5a, 0xc4, 0x19,
	0x33, 0x85, 0x9a, 0x25, 0xae, 0x6d, 0xd1, 0xe1, 0x0c, 0x24, 0x1b, 0x70, 0x21, 0x93, 0xf6, 0x79,
	0xf1, 0xcb, 0xdf, 0x1b, 0xe4, 0x2a, 0x00, 0x9e, 0xe6, 0x42, 0xa1, 0xa6, 0xcc, 0x04, 0x0d, 0x47,
	0xad, 0x96, 0xc8, 0x7d, 0x73, 0x83, 0x43, 0x63, 0xb6, 0xf1, 0xc8, 0x16, 0x5c, 0x3e, 0x38, 0xbc,
	0xff, 0x35, 0x1d, 0x0e, 0x9e, 0x1d, 0xd2, 0x27, 0xdf, 0x0c, 0x8f, 0x0e, 0x1f, 0x0c, 0xbe, 0x1c,
	0x1c, 0x1e, 0x74, 0x96, 0x08, 0x81, 0xb5, 0x05, 0x75, 0xf7, 0xab, 0xc1, 0x7e, 0xa7, 0x42, 0x2e,
	0xc1, 0xfa, 0x02, 0xbb, 0x73, 0xdb, 0x82, 0x55, 0xb2, 0x01, 0x9d, 0x05, 0xf8, 0xd9, 0x2d, 0x87,
	0xd6, 0xf6, 0xef, 0xbc, 0x7c, 0xd3, 0xad, 0xbc, 0x7a, 0xd3, 0xad, 0xfc, 0xf1, 0xa6, 0x5b, 0xf9,
	0xfe, 0x6d, 0x77, 0xe9, 0xd5, 0xdb, 0xee, 0xd2, 0x6f, 0x6f, 0xbb, 0x4b, 0xcf, 0xb6, 0xe6, 0x6f,
	0xfd, 0xe9, 0xe2, 0xd9, 0x77, 0x6f, 0xfe, 0xf1, 0xb2, 0x7b, 0xad, 0xef, 0xfc, 0x1d, 0x00, 0x00,
	0xff, 0xff, 0xce, 0x03, 0xbe, 0x44, 0x18, 0x08, 0x00, 0x00,
}

func (m *Deal) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *Deal) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *Deal) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.DealSize != 0 {
		i = encodeVarintTypes(dAtA, i, uint64(m.DealSize))
		i--
		dAtA[i] = 0x68
	}
	{
		size := m.MaxMonthlySpend.Size()
		i -= size
		if _, err := m.MaxMonthlySpend.MarshalTo(dAtA[i:]); err != nil {
			return 0, err
		}
		i = encodeVarintTypes(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0x62
	if len(m.ServiceHint) > 0 {
		i -= len(m.ServiceHint)
		copy(dAtA[i:], m.ServiceHint)
		i = encodeVarintTypes(dAtA, i, uint64(len(m.ServiceHint)))
		i--
		dAtA[i] = 0x5a
	}
	if m.CurrentReplication != 0 {
		i = encodeVarintTypes(dAtA, i, uint64(m.CurrentReplication))
		i--
		dAtA[i] = 0x50
	}
	if m.RedundancyMode != 0 {
		i = encodeVarintTypes(dAtA, i, uint64(m.RedundancyMode))
		i--
		dAtA[i] = 0x48
	}
	if len(m.Providers) > 0 {
		for iNdEx := len(m.Providers) - 1; iNdEx >= 0; iNdEx-- {
			i -= len(m.Providers[iNdEx])
			copy(dAtA[i:], m.Providers[iNdEx])
			i = encodeVarintTypes(dAtA, i, uint64(len(m.Providers[iNdEx])))
			i--
			dAtA[i] = 0x42
		}
	}
	if m.EndBlock != 0 {
		i = encodeVarintTypes(dAtA, i, uint64(m.EndBlock))
		i--
		dAtA[i] = 0x38
	}
	if m.StartBlock != 0 {
		i = encodeVarintTypes(dAtA, i, uint64(m.StartBlock))
		i--
		dAtA[i] = 0x30
	}
	{
		size := m.EscrowBalance.Size()
		i -= size
		if _, err := m.EscrowBalance.MarshalTo(dAtA[i:]); err != nil {
			return 0, err
		}
		i = encodeVarintTypes(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0x2a
	if len(m.Owner) > 0 {
		i -= len(m.Owner)
		copy(dAtA[i:], m.Owner)
		i = encodeVarintTypes(dAtA, i, uint64(len(m.Owner)))
		i--
		dAtA[i] = 0x22
	}
	if m.Size_ != 0 {
		i = encodeVarintTypes(dAtA, i, uint64(m.Size_))
		i--
		dAtA[i] = 0x18
	}
	if len(m.Cid) > 0 {
		i -= len(m.Cid)
		copy(dAtA[i:], m.Cid)
		i = encodeVarintTypes(dAtA, i, uint64(len(m.Cid)))
		i--
		dAtA[i] = 0x12
	}
	if m.Id != 0 {
		i = encodeVarintTypes(dAtA, i, uint64(m.Id))
		i--
		dAtA[i] = 0x8
	}
	return len(dAtA) - i, nil
}

func (m *DealHeatState) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *DealHeatState) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *DealHeatState) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.LastUpdateHeight != 0 {
		i = encodeVarintTypes(dAtA, i, uint64(m.LastUpdateHeight))
		i--
		dAtA[i] = 0x18
	}
	if m.FailedChallengesTotal != 0 {
		i = encodeVarintTypes(dAtA, i, uint64(m.FailedChallengesTotal))
		i--
		dAtA[i] = 0x10
	}
	if m.BytesServedTotal != 0 {
		i = encodeVarintTypes(dAtA, i, uint64(m.BytesServedTotal))
		i--
		dAtA[i] = 0x8
	}
	return len(dAtA) - i, nil
}

func (m *Provider) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *Provider) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *Provider) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.ReputationScore != 0 {
		i = encodeVarintTypes(dAtA, i, uint64(m.ReputationScore))
		i--
		dAtA[i] = 0x30
	}
	if len(m.Status) > 0 {
		i -= len(m.Status)
		copy(dAtA[i:], m.Status)
		i = encodeVarintTypes(dAtA, i, uint64(len(m.Status)))
		i--
		dAtA[i] = 0x2a
	}
	if len(m.Capabilities) > 0 {
		i -= len(m.Capabilities)
		copy(dAtA[i:], m.Capabilities)
		i = encodeVarintTypes(dAtA, i, uint64(len(m.Capabilities)))
		i--
		dAtA[i] = 0x22
	}
	if m.UsedStorage != 0 {
		i = encodeVarintTypes(dAtA, i, uint64(m.UsedStorage))
		i--
		dAtA[i] = 0x18
	}
	if m.TotalStorage != 0 {
		i = encodeVarintTypes(dAtA, i, uint64(m.TotalStorage))
		i--
		dAtA[i] = 0x10
	}
	if len(m.Address) > 0 {
		i -= len(m.Address)
		copy(dAtA[i:], m.Address)
		i = encodeVarintTypes(dAtA, i, uint64(len(m.Address)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *VirtualStripe) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *VirtualStripe) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *VirtualStripe) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.OverlayProviders) > 0 {
		for iNdEx := len(m.OverlayProviders) - 1; iNdEx >= 0; iNdEx-- {
			i -= len(m.OverlayProviders[iNdEx])
			copy(dAtA[i:], m.OverlayProviders[iNdEx])
			i = encodeVarintTypes(dAtA, i, uint64(len(m.OverlayProviders[iNdEx])))
			i--
			dAtA[i] = 0x1a
		}
	}
	if m.StripeIndex != 0 {
		i = encodeVarintTypes(dAtA, i, uint64(m.StripeIndex))
		i--
		dAtA[i] = 0x10
	}
	if m.DealId != 0 {
		i = encodeVarintTypes(dAtA, i, uint64(m.DealId))
		i--
		dAtA[i] = 0x8
	}
	return len(dAtA) - i, nil
}

func (m *KzgProof) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *KzgProof) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *KzgProof) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.KzgOpeningProof) > 0 {
		i -= len(m.KzgOpeningProof)
		copy(dAtA[i:], m.KzgOpeningProof)
		i = encodeVarintTypes(dAtA, i, uint64(len(m.KzgOpeningProof)))
		i--
		dAtA[i] = 0x3a
	}
	if len(m.YValue) > 0 {
		i -= len(m.YValue)
		copy(dAtA[i:], m.YValue)
		i = encodeVarintTypes(dAtA, i, uint64(len(m.YValue)))
		i--
		dAtA[i] = 0x32
	}
	if len(m.ZValue) > 0 {
		i -= len(m.ZValue)
		copy(dAtA[i:], m.ZValue)
		i = encodeVarintTypes(dAtA, i, uint64(len(m.ZValue)))
		i--
		dAtA[i] = 0x2a
	}
	if m.ChallengedKzgCommitmentIndex != 0 {
		i = encodeVarintTypes(dAtA, i, uint64(m.ChallengedKzgCommitmentIndex))
		i--
		dAtA[i] = 0x20
	}
	if len(m.ChallengedKzgCommitmentMerklePath) > 0 {
		for iNdEx := len(m.ChallengedKzgCommitmentMerklePath) - 1; iNdEx >= 0; iNdEx-- {
			i -= len(m.ChallengedKzgCommitmentMerklePath[iNdEx])
			copy(dAtA[i:], m.ChallengedKzgCommitmentMerklePath[iNdEx])
			i = encodeVarintTypes(dAtA, i, uint64(len(m.ChallengedKzgCommitmentMerklePath[iNdEx])))
			i--
			dAtA[i] = 0x1a
		}
	}
	if len(m.ChallengedKzgCommitment) > 0 {
		i -= len(m.ChallengedKzgCommitment)
		copy(dAtA[i:], m.ChallengedKzgCommitment)
		i = encodeVarintTypes(dAtA, i, uint64(len(m.ChallengedKzgCommitment)))
		i--
		dAtA[i] = 0x12
	}
	if len(m.MduMerkleRoot) > 0 {
		i -= len(m.MduMerkleRoot)
		copy(dAtA[i:], m.MduMerkleRoot)
		i = encodeVarintTypes(dAtA, i, uint64(len(m.MduMerkleRoot)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *RetrievalReceipt) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *RetrievalReceipt) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *RetrievalReceipt) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.ExpiresAt != 0 {
		i = encodeVarintTypes(dAtA, i, uint64(m.ExpiresAt))
		i--
		dAtA[i] = 0x40
	}
	if m.Nonce != 0 {
		i = encodeVarintTypes(dAtA, i, uint64(m.Nonce))
		i--
		dAtA[i] = 0x38
	}
	if len(m.UserSignature) > 0 {
		i -= len(m.UserSignature)
		copy(dAtA[i:], m.UserSignature)
		i = encodeVarintTypes(dAtA, i, uint64(len(m.UserSignature)))
		i--
		dAtA[i] = 0x32
	}
	{
		size, err := m.ProofDetails.MarshalToSizedBuffer(dAtA[:i])
		if err != nil {
			return 0, err
		}
		i -= size
		i = encodeVarintTypes(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0x2a
	if m.BytesServed != 0 {
		i = encodeVarintTypes(dAtA, i, uint64(m.BytesServed))
		i--
		dAtA[i] = 0x20
	}
	if len(m.Provider) > 0 {
		i -= len(m.Provider)
		copy(dAtA[i:], m.Provider)
		i = encodeVarintTypes(dAtA, i, uint64(len(m.Provider)))
		i--
		dAtA[i] = 0x1a
	}
	if m.EpochId != 0 {
		i = encodeVarintTypes(dAtA, i, uint64(m.EpochId))
		i--
		dAtA[i] = 0x10
	}
	if m.DealId != 0 {
		i = encodeVarintTypes(dAtA, i, uint64(m.DealId))
		i--
		dAtA[i] = 0x8
	}
	return len(dAtA) - i, nil
}

func encodeVarintTypes(dAtA []byte, offset int, v uint64) int {
	offset -= sovTypes(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *Deal) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.Id != 0 {
		n += 1 + sovTypes(uint64(m.Id))
	}
	l = len(m.Cid)
	if l > 0 {
		n += 1 + l + sovTypes(uint64(l))
	}
	if m.Size_ != 0 {
		n += 1 + sovTypes(uint64(m.Size_))
	}
	l = len(m.Owner)
	if l > 0 {
		n += 1 + l + sovTypes(uint64(l))
	}
	l = m.EscrowBalance.Size()
	n += 1 + l + sovTypes(uint64(l))
	if m.StartBlock != 0 {
		n += 1 + sovTypes(uint64(m.StartBlock))
	}
	if m.EndBlock != 0 {
		n += 1 + sovTypes(uint64(m.EndBlock))
	}
	if len(m.Providers) > 0 {
		for _, s := range m.Providers {
			l = len(s)
			n += 1 + l + sovTypes(uint64(l))
		}
	}
	if m.RedundancyMode != 0 {
		n += 1 + sovTypes(uint64(m.RedundancyMode))
	}
	if m.CurrentReplication != 0 {
		n += 1 + sovTypes(uint64(m.CurrentReplication))
	}
	l = len(m.ServiceHint)
	if l > 0 {
		n += 1 + l + sovTypes(uint64(l))
	}
	l = m.MaxMonthlySpend.Size()
	n += 1 + l + sovTypes(uint64(l))
	if m.DealSize != 0 {
		n += 1 + sovTypes(uint64(m.DealSize))
	}
	return n
}

func (m *DealHeatState) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.BytesServedTotal != 0 {
		n += 1 + sovTypes(uint64(m.BytesServedTotal))
	}
	if m.FailedChallengesTotal != 0 {
		n += 1 + sovTypes(uint64(m.FailedChallengesTotal))
	}
	if m.LastUpdateHeight != 0 {
		n += 1 + sovTypes(uint64(m.LastUpdateHeight))
	}
	return n
}

func (m *Provider) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Address)
	if l > 0 {
		n += 1 + l + sovTypes(uint64(l))
	}
	if m.TotalStorage != 0 {
		n += 1 + sovTypes(uint64(m.TotalStorage))
	}
	if m.UsedStorage != 0 {
		n += 1 + sovTypes(uint64(m.UsedStorage))
	}
	l = len(m.Capabilities)
	if l > 0 {
		n += 1 + l + sovTypes(uint64(l))
	}
	l = len(m.Status)
	if l > 0 {
		n += 1 + l + sovTypes(uint64(l))
	}
	if m.ReputationScore != 0 {
		n += 1 + sovTypes(uint64(m.ReputationScore))
	}
	return n
}

func (m *VirtualStripe) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.DealId != 0 {
		n += 1 + sovTypes(uint64(m.DealId))
	}
	if m.StripeIndex != 0 {
		n += 1 + sovTypes(uint64(m.StripeIndex))
	}
	if len(m.OverlayProviders) > 0 {
		for _, s := range m.OverlayProviders {
			l = len(s)
			n += 1 + l + sovTypes(uint64(l))
		}
	}
	return n
}

func (m *KzgProof) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.MduMerkleRoot)
	if l > 0 {
		n += 1 + l + sovTypes(uint64(l))
	}
	l = len(m.ChallengedKzgCommitment)
	if l > 0 {
		n += 1 + l + sovTypes(uint64(l))
	}
	if len(m.ChallengedKzgCommitmentMerklePath) > 0 {
		for _, b := range m.ChallengedKzgCommitmentMerklePath {
			l = len(b)
			n += 1 + l + sovTypes(uint64(l))
		}
	}
	if m.ChallengedKzgCommitmentIndex != 0 {
		n += 1 + sovTypes(uint64(m.ChallengedKzgCommitmentIndex))
	}
	l = len(m.ZValue)
	if l > 0 {
		n += 1 + l + sovTypes(uint64(l))
	}
	l = len(m.YValue)
	if l > 0 {
		n += 1 + l + sovTypes(uint64(l))
	}
	l = len(m.KzgOpeningProof)
	if l > 0 {
		n += 1 + l + sovTypes(uint64(l))
	}
	return n
}

func (m *RetrievalReceipt) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.DealId != 0 {
		n += 1 + sovTypes(uint64(m.DealId))
	}
	if m.EpochId != 0 {
		n += 1 + sovTypes(uint64(m.EpochId))
	}
	l = len(m.Provider)
	if l > 0 {
		n += 1 + l + sovTypes(uint64(l))
	}
	if m.BytesServed != 0 {
		n += 1 + sovTypes(uint64(m.BytesServed))
	}
	l = m.ProofDetails.Size()
	n += 1 + l + sovTypes(uint64(l))
	l = len(m.UserSignature)
	if l > 0 {
		n += 1 + l + sovTypes(uint64(l))
	}
	if m.Nonce != 0 {
		n += 1 + sovTypes(uint64(m.Nonce))
	}
	if m.ExpiresAt != 0 {
		n += 1 + sovTypes(uint64(m.ExpiresAt))
	}
	return n
}

func sovTypes(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozTypes(x uint64) (n int) {
	return sovTypes(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *Deal) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTypes
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: Deal: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: Deal: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Id", wireType)
			}
			m.Id = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTypes
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Id |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Cid", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTypes
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTypes
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTypes
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Cid = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 3:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Size_", wireType)
			}
			m.Size_ = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTypes
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Size_ |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 4:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Owner", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTypes
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTypes
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTypes
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Owner = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 5:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field EscrowBalance", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTypes
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTypes
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTypes
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.EscrowBalance.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 6:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field StartBlock", wireType)
			}
			m.StartBlock = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTypes
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.StartBlock |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 7:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field EndBlock", wireType)
			}
			m.EndBlock = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTypes
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.EndBlock |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 8:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Providers", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTypes
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTypes
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTypes
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Providers = append(m.Providers, string(dAtA[iNdEx:postIndex]))
			iNdEx = postIndex
		case 9:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field RedundancyMode", wireType)
			}
			m.RedundancyMode = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTypes
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.RedundancyMode |= uint32(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 10:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field CurrentReplication", wireType)
			}
			m.CurrentReplication = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTypes
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.CurrentReplication |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 11:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field ServiceHint", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTypes
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTypes
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTypes
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.ServiceHint = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 12:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field MaxMonthlySpend", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTypes
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTypes
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTypes
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.MaxMonthlySpend.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 13:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field DealSize", wireType)
			}
			m.DealSize = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTypes
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.DealSize |= DealSize(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		default:
			iNdEx = preIndex
			skippy, err := skipTypes(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTypes
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *DealHeatState) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTypes
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: DealHeatState: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: DealHeatState: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field BytesServedTotal", wireType)
			}
			m.BytesServedTotal = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTypes
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.BytesServedTotal |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 2:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field FailedChallengesTotal", wireType)
			}
			m.FailedChallengesTotal = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTypes
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.FailedChallengesTotal |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 3:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field LastUpdateHeight", wireType)
			}
			m.LastUpdateHeight = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTypes
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.LastUpdateHeight |= int64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		default:
			iNdEx = preIndex
			skippy, err := skipTypes(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTypes
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *Provider) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTypes
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: Provider: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: Provider: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Address", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTypes
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTypes
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTypes
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Address = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field TotalStorage", wireType)
			}
			m.TotalStorage = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTypes
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.TotalStorage |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 3:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field UsedStorage", wireType)
			}
			m.UsedStorage = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTypes
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.UsedStorage |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 4:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Capabilities", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTypes
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTypes
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTypes
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Capabilities = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 5:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Status", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTypes
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTypes
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTypes
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Status = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 6:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field ReputationScore", wireType)
			}
			m.ReputationScore = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTypes
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.ReputationScore |= int64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		default:
			iNdEx = preIndex
			skippy, err := skipTypes(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTypes
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *VirtualStripe) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTypes
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: VirtualStripe: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: VirtualStripe: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field DealId", wireType)
			}
			m.DealId = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTypes
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.DealId |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 2:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field StripeIndex", wireType)
			}
			m.StripeIndex = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTypes
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.StripeIndex |= uint32(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field OverlayProviders", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTypes
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTypes
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTypes
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.OverlayProviders = append(m.OverlayProviders, string(dAtA[iNdEx:postIndex]))
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipTypes(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTypes
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *KzgProof) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTypes
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: KzgProof: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: KzgProof: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field MduMerkleRoot", wireType)
			}
			var byteLen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTypes
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				byteLen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if byteLen < 0 {
				return ErrInvalidLengthTypes
			}
			postIndex := iNdEx + byteLen
			if postIndex < 0 {
				return ErrInvalidLengthTypes
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.MduMerkleRoot = append(m.MduMerkleRoot[:0], dAtA[iNdEx:postIndex]...)
			if m.MduMerkleRoot == nil {
				m.MduMerkleRoot = []byte{}
			}
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field ChallengedKzgCommitment", wireType)
			}
			var byteLen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTypes
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				byteLen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if byteLen < 0 {
				return ErrInvalidLengthTypes
			}
			postIndex := iNdEx + byteLen
			if postIndex < 0 {
				return ErrInvalidLengthTypes
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.ChallengedKzgCommitment = append(m.ChallengedKzgCommitment[:0], dAtA[iNdEx:postIndex]...)
			if m.ChallengedKzgCommitment == nil {
				m.ChallengedKzgCommitment = []byte{}
			}
			iNdEx = postIndex
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field ChallengedKzgCommitmentMerklePath", wireType)
			}
			var byteLen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTypes
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				byteLen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if byteLen < 0 {
				return ErrInvalidLengthTypes
			}
			postIndex := iNdEx + byteLen
			if postIndex < 0 {
				return ErrInvalidLengthTypes
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.ChallengedKzgCommitmentMerklePath = append(m.ChallengedKzgCommitmentMerklePath, make([]byte, postIndex-iNdEx))
			copy(m.ChallengedKzgCommitmentMerklePath[len(m.ChallengedKzgCommitmentMerklePath)-1], dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 4:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field ChallengedKzgCommitmentIndex", wireType)
			}
			m.ChallengedKzgCommitmentIndex = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTypes
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.ChallengedKzgCommitmentIndex |= uint32(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 5:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field ZValue", wireType)
			}
			var byteLen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTypes
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				byteLen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if byteLen < 0 {
				return ErrInvalidLengthTypes
			}
			postIndex := iNdEx + byteLen
			if postIndex < 0 {
				return ErrInvalidLengthTypes
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.ZValue = append(m.ZValue[:0], dAtA[iNdEx:postIndex]...)
			if m.ZValue == nil {
				m.ZValue = []byte{}
			}
			iNdEx = postIndex
		case 6:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field YValue", wireType)
			}
			var byteLen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTypes
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				byteLen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if byteLen < 0 {
				return ErrInvalidLengthTypes
			}
			postIndex := iNdEx + byteLen
			if postIndex < 0 {
				return ErrInvalidLengthTypes
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.YValue = append(m.YValue[:0], dAtA[iNdEx:postIndex]...)
			if m.YValue == nil {
				m.YValue = []byte{}
			}
			iNdEx = postIndex
		case 7:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field KzgOpeningProof", wireType)
			}
			var byteLen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTypes
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				byteLen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if byteLen < 0 {
				return ErrInvalidLengthTypes
			}
			postIndex := iNdEx + byteLen
			if postIndex < 0 {
				return ErrInvalidLengthTypes
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.KzgOpeningProof = append(m.KzgOpeningProof[:0], dAtA[iNdEx:postIndex]...)
			if m.KzgOpeningProof == nil {
				m.KzgOpeningProof = []byte{}
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipTypes(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTypes
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *RetrievalReceipt) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTypes
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: RetrievalReceipt: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: RetrievalReceipt: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field DealId", wireType)
			}
			m.DealId = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTypes
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.DealId |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 2:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field EpochId", wireType)
			}
			m.EpochId = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTypes
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.EpochId |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Provider", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTypes
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTypes
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTypes
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Provider = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 4:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field BytesServed", wireType)
			}
			m.BytesServed = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTypes
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.BytesServed |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 5:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field ProofDetails", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTypes
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthTypes
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthTypes
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.ProofDetails.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 6:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field UserSignature", wireType)
			}
			var byteLen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTypes
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				byteLen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if byteLen < 0 {
				return ErrInvalidLengthTypes
			}
			postIndex := iNdEx + byteLen
			if postIndex < 0 {
				return ErrInvalidLengthTypes
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.UserSignature = append(m.UserSignature[:0], dAtA[iNdEx:postIndex]...)
			if m.UserSignature == nil {
				m.UserSignature = []byte{}
			}
			iNdEx = postIndex
		case 7:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Nonce", wireType)
			}
			m.Nonce = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTypes
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Nonce |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 8:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field ExpiresAt", wireType)
			}
			m.ExpiresAt = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTypes
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.ExpiresAt |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		default:
			iNdEx = preIndex
			skippy, err := skipTypes(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTypes
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipTypes(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowTypes
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowTypes
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowTypes
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthTypes
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupTypes
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthTypes
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthTypes        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowTypes          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupTypes = fmt.Errorf("proto: unexpected end of group")
)
