#!/usr/bin/env bash
set -euo pipefail

ROOT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
cd "$ROOT_DIR"

CHAIN_ID=20260211 \
EVM_CHAIN_ID=20260211 \
NIL_LOCAL_PROVIDER_COUNT="${NIL_LOCAL_PROVIDER_COUNT:-3}" \
NIL_START_WEB=1 \
NIL_START_FAUCET=1 \
NIL_REQUIRE_ONCHAIN_SESSION="${NIL_REQUIRE_ONCHAIN_SESSION:-0}" \
NIL_USER_GATEWAY_PROXY_MODE="${NIL_USER_GATEWAY_PROXY_MODE:-0}" \
./scripts/run_local_stack.sh start
