#!/usr/bin/env bash
set -euo pipefail

ROOT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
cd "$ROOT_DIR"

CHAIN_ID=20260211 \
EVM_CHAIN_ID=20260211 \
POLYSTORE_LOCAL_PROVIDER_COUNT="${POLYSTORE_LOCAL_PROVIDER_COUNT:-3}" \
POLYSTORE_START_WEB=1 \
POLYSTORE_START_FAUCET=1 \
POLYSTORE_REQUIRE_ONCHAIN_SESSION="${POLYSTORE_REQUIRE_ONCHAIN_SESSION:-0}" \
POLYSTORE_USER_GATEWAY_PROXY_MODE="${POLYSTORE_USER_GATEWAY_PROXY_MODE:-0}" \
./scripts/run_local_stack.sh start
