"""
PolyStore economic modeling (Jan 2026 draft)
------------------------------------------

This is an *off-chain* exploratory model meant to help calibrate deterministic on-chain parameters.

It implements:
- A data-scaled base reward pool: issuance ∝ (storage_price × active_bytes) × emission_bps(t)
- A simple "cost-of-service" equilibrium mapping that converts NIL-denominated fees+rewards into USD
  by setting token_price_usd so that providers (in aggregate) can cover an assumed USD cost curve.

IMPORTANT:
- On-chain PolyStore does not use USD or fiat oracles.
- USD here is only a modeling convenience to reason about provider costs and user affordability.

Author: generated by GPT-5.2 Pro
License: MIT-style (you can copy into repo)
"""
from __future__ import annotations

from dataclasses import dataclass
from typing import Dict, Iterable, Tuple, List
import math

PIB_TO_GIB: float = 1024.0 ** 2  # 1 PiB = 1,048,576 GiB (binary)
MONTHS_PER_YEAR: int = 12

@dataclass(frozen=True)
class EmissionSchedule:
    """
    Continuous halving-to-tail schedule expressed in basis points (bps).

    bps(t) = tail_bps + (start_bps - tail_bps) * 2^(-t / halving_months)

    - start_bps: bootstrap subsidy intensity
    - tail_bps: long-run bounded tail emission (bps of notional slot rent)
    - halving_months: how quickly bootstrap subsidy halves (the "excess over tail" halves)
    """
    start_bps: float = 425.0
    tail_bps: float = 25.0
    halving_months: float = 12.0

    def bps(self, month: float) -> float:
        excess = max(0.0, self.start_bps - self.tail_bps)
        return self.tail_bps + excess * (2.0 ** (-month / self.halving_months))

@dataclass(frozen=True)
class GrowthScenario:
    """
    Logistic growth of active storage in PiB:
      A(t) = cap / (1 + exp(-k*(t - t0)))

    Parameters:
      cap_pib: carrying capacity
      k: slope (per month)
      t0: midpoint month (A(t0)=cap/2)
    """
    name: str
    cap_pib: float
    k: float
    t0: float

    def active_pib(self, month: float) -> float:
        return self.cap_pib / (1.0 + math.exp(-self.k * (month - self.t0)))

@dataclass(frozen=True)
class CostCurve:
    """
    Economies-of-scale cost curve (USD per GiB-month):
      cost_usd_per_gibmonth = cost_at_1pib * (active_pib)^(-alpha)

    alpha ~ 0.1 gives modest cost improvement with scale.
    """
    cost_at_1pib_usd_per_gibmonth: float = 0.007924556154438645
    alpha: float = 0.1

    def cost_usd_per_gibmonth(self, active_pib: float) -> float:
        # Avoid singularity near 0; clamp at tiny epsilon.
        a = max(active_pib, 1e-6)
        return self.cost_at_1pib_usd_per_gibmonth * (a ** (-self.alpha))

@dataclass(frozen=True)
class MarketAssumptions:
    """
    The on-chain storage_price is in NIL per byte per block.
    In the modeling layer we normalize it to NIL per GiB-month for readability.

    storage_price_nil_per_gibmonth:
      A normalization constant used to compute fee and issuance flows in NIL.

    Interpretation:
      - If storage_price_nil_per_gibmonth increases (because the controller raises it),
        users pay more NIL per GiB-month, and issuance (bps of rent) also increases.
    """
    storage_price_nil_per_gibmonth: float = 1.0

def issuance_per_gibmonth_nil(storage_price_nil_per_gibmonth: float, bps: float) -> float:
    return storage_price_nil_per_gibmonth * (bps / 10_000.0)

def monthly_issuance_nil(active_pib: float, storage_price_nil_per_gibmonth: float, bps: float) -> float:
    active_gib = active_pib * PIB_TO_GIB
    return active_gib * issuance_per_gibmonth_nil(storage_price_nil_per_gibmonth, bps)

def equilibrium_token_price_usd(
    cost_usd_per_gibmonth: float,
    storage_price_nil_per_gibmonth: float,
    bps: float,
) -> float:
    """
    Simplified equilibrium mapping:

    Providers receive:
      - user storage fees: storage_price_nil_per_gibmonth (NIL per GiB-month)
      - protocol issuance: storage_price_nil_per_gibmonth * bps/10,000 (NIL per GiB-month)

    Total NIL income per GiB-month = storage_price_nil_per_gibmonth * (1 + bps/10,000)

    Set token_price_usd so that income_usd == assumed cost_usd_per_gibmonth:
      token_price_usd = cost_usd_per_gibmonth / [storage_price_nil_per_gibmonth * (1 + bps/10,000)]
    """
    denom = storage_price_nil_per_gibmonth * (1.0 + bps / 10_000.0)
    return cost_usd_per_gibmonth / denom

def simulate_scenarios(
    months: Iterable[int],
    scenarios: List[GrowthScenario],
    emission: EmissionSchedule,
    cost_curve: CostCurve,
    market: MarketAssumptions,
) -> List[Dict]:
    rows: List[Dict] = []
    for s in scenarios:
        for m in months:
            active_pib = s.active_pib(m)
            bps = emission.bps(m)
            cost = cost_curve.cost_usd_per_gibmonth(active_pib)
            token_price = equilibrium_token_price_usd(cost, market.storage_price_nil_per_gibmonth, bps)
            storage_price_usd = market.storage_price_nil_per_gibmonth * token_price
            issuance = monthly_issuance_nil(active_pib, market.storage_price_nil_per_gibmonth, bps)
            rows.append({
                "scenario": s.name,
                "month": m,
                "active_pib": active_pib,
                "bps": bps,
                "cost_usd_per_gibmonth": cost,
                "token_price_usd": token_price,
                "storage_price_usd_per_gibmonth": storage_price_usd,
                "issuance_monthly_nil": issuance,
            })
    return rows

def apply_demand_shock(
    baseline_active_pib: List[float],
    shock_month: int,
    drop_fraction: float,
    recovery_half_life_months: float = 6.0,
) -> List[float]:
    """
    Apply a one-off demand shock (active storage contracts) with exponential recovery.
    """
    out = baseline_active_pib.copy()
    if shock_month < 0 or shock_month >= len(out):
        return out
    # Instant drop at shock month
    out[shock_month] = out[shock_month] * (1.0 - drop_fraction)
    # Recovery thereafter toward baseline with exponential half-life
    for m in range(shock_month + 1, len(out)):
        # fraction recovered since shock
        t = m - shock_month
        recover_frac = 1.0 - (0.5 ** (t / recovery_half_life_months))
        out[m] = out[shock_month] + recover_frac * (baseline_active_pib[m] - out[shock_month])
    return out

def apply_cost_shock(
    baseline_cost_at_1pib: float,
    month: int,
    shock_month: int,
    shock_multiplier: float,
    decay_half_life_months: float = 9.0,
) -> float:
    """
    Increase cost_at_1pib by a multiplier at shock_month, decaying back to baseline.
    """
    if month < shock_month:
        return baseline_cost_at_1pib
    t = month - shock_month
    mult = 1.0 + (shock_multiplier - 1.0) * (0.5 ** (t / decay_half_life_months))
    return baseline_cost_at_1pib * mult
